ou_sets = {'Alakazam': [
    {'Name': 'Alakazam', 'Gender': None, 'Item': 'Alakazite', 'Ability': 'Magic Guard', 'Shiny': None, 'HP': None,
     'Atk': None, 'Def': '4', 'SpA': '252', 'SpD': None, 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Timid', 'Move1': 'Psychic', 'Move2': 'Focus Blast',
     'Move3': 'Recover', 'Move4': 'Shadow Ball', 'Lv': 100},
    {'Name': 'Alakazam', 'Gender': None, 'Item': 'Life Orb', 'Ability': 'Magic Guard', 'Shiny': None, 'HP': None,
     'Atk': None, 'Def': None, 'SpA': '252', 'SpD': '4', 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Timid', 'Move1': 'Psychic', 'Move2': 'Focus Blast',
     'Move3': 'Shadow Ball', 'Move4': 'Hidden Power Fire', 'Lv': 100}], 'Azumarill': [
    {'Name': 'Azumarill', 'Gender': None, 'Item': 'Normalium Z', 'Ability': 'Huge Power', 'Shiny': None, 'HP': '4',
     'Atk': '252', 'Def': None, 'SpA': None, 'SpD': None, 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Adamant', 'Move1': 'Belly Drum', 'Move2': 'Aqua Jet',
     'Move3': 'Play Rough', 'Move4': 'Knock Off', 'Lv': 100}], 'Blacephalon': [
    {'Name': 'Blacephalon', 'Gender': None, 'Item': 'Choice Specs', 'Ability': 'Beast Boost', 'Shiny': None, 'HP': None,
     'Atk': None, 'Def': None, 'SpA': '252', 'SpD': '4', 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Timid', 'Move1': 'Fire Blast', 'Move2': 'Shadow Ball',
     'Move3': 'Hidden Power Ground', 'Move4': 'Trick', 'Lv': 100},
    {'Name': 'Blacephalon', 'Gender': None, 'Item': 'Ghostium Z', 'Ability': 'Beast Boost', 'Shiny': None, 'HP': '232',
     'Atk': None, 'Def': '4', 'SpA': '20', 'SpD': None, 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Timid', 'Move1': 'Flamethrower', 'Move2': 'Shadow Ball',
     'Move3': 'Substitute', 'Move4': 'Calm Mind', 'Lv': 100}], 'Celesteela': [
    {'Name': 'Celesteela', 'Gender': None, 'Item': 'Leftovers', 'Ability': 'Beast Boost', 'Shiny': None, 'HP': '248',
     'Atk': None, 'Def': '28', 'SpA': None, 'SpD': '232', 'Spe': None, 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Sassy', 'Move1': 'Leech Seed', 'Move2': 'Protect',
     'Move3': 'Heavy Slam', 'Move4': 'Flamethrower', 'Lv': 100}], 'Chansey': [
    {'Name': 'Chansey', 'Gender': None, 'Item': 'Eviolite', 'Ability': 'Natural Cure', 'Shiny': None, 'HP': '248',
     'Atk': None, 'Def': '252', 'SpA': None, 'SpD': '8', 'Spe': None, 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Bold', 'Move1': 'Seismic Toss', 'Move2': 'Toxic',
     'Move3': 'Stealth Rock', 'Move4': 'Soft-Boiled', 'Lv': 100}], 'Charizard': [
    {'Name': 'Charizard', 'Gender': None, 'Item': 'Charizardite X', 'Ability': 'Blaze', 'Shiny': None, 'HP': None,
     'Atk': '252', 'Def': None, 'SpA': None, 'SpD': '4', 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Jolly', 'Move1': 'Dragon Dance', 'Move2': 'Flare Blitz',
     'Move3': 'Earthquake', 'Move4': 'Roost', 'Lv': 100},
    {'Name': 'Charizard', 'Gender': None, 'Item': 'Charizardite Y', 'Ability': 'Blaze', 'Shiny': None, 'HP': None,
     'Atk': None, 'Def': '4', 'SpA': '252', 'SpD': None, 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Timid', 'Move1': 'Flamethrower', 'Move2': 'Focus Blast',
     'Move3': 'Solar Beam', 'Move4': 'Roost', 'Lv': 100},
    {'Name': 'Charizard', 'Gender': None, 'Item': 'Charizardite X', 'Ability': 'Blaze', 'Shiny': None, 'HP': None,
     'Atk': '252', 'Def': None, 'SpA': None, 'SpD': '4', 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Jolly', 'Move1': 'Flare Blitz', 'Move2': 'Outrage',
     'Move3': 'Earthquake', 'Move4': 'Roost', 'Lv': 100}], 'Clefable': [
    {'Name': 'Clefable', 'Gender': None, 'Item': 'Leftovers', 'Ability': 'Magic Guard', 'Shiny': None, 'HP': '252',
     'Atk': None, 'Def': '252', 'SpA': None, 'SpD': '4', 'Spe': None, 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Bold', 'Move1': 'Stealth Rock', 'Move2': 'Moonblast',
     'Move3': 'Soft-Boiled', 'Move4': 'Calm Mind', 'Lv': 100},
    {'Name': 'Clefable', 'Gender': None, 'Item': 'Life Orb', 'Ability': 'Magic Guard', 'Shiny': None, 'HP': '80',
     'Atk': None, 'Def': None, 'SpA': '252', 'SpD': None, 'Spe': '176', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Modest', 'Move1': 'Moonblast', 'Move2': 'Thunderbolt',
     'Move3': 'Fire Blast', 'Move4': 'Soft-Boiled', 'Lv': 100},
    {'Name': 'Clefable', 'Gender': None, 'Item': 'Leftovers', 'Ability': 'Unaware', 'Shiny': None, 'HP': '252',
     'Atk': None, 'Def': '252', 'SpA': None, 'SpD': '4', 'Spe': None, 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Bold', 'Move1': 'Calm Mind', 'Move2': 'Moonblast',
     'Move3': 'Wish', 'Move4': 'Protect', 'Lv': 100}], 'Diancie': [
    {'Name': 'Diancie', 'Gender': None, 'Item': 'Diancite', 'Ability': 'Clear Body', 'Shiny': None, 'HP': None,
     'Atk': None, 'Def': None, 'SpA': '252', 'SpD': '4', 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Hasty', 'Move1': 'Stealth Rock', 'Move2': 'Moonblast',
     'Move3': 'Diamond Storm', 'Move4': 'Earth Power', 'Lv': 100}], 'Excadrill': [
    {'Name': 'Excadrill', 'Gender': None, 'Item': 'Steelium Z', 'Ability': 'Sand Rush', 'Shiny': None, 'HP': '4',
     'Atk': '252', 'Def': None, 'SpA': None, 'SpD': None, 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Jolly', 'Move1': 'Swords Dance', 'Move2': 'Earthquake',
     'Move3': 'Iron Head', 'Move4': 'Rapid Spin', 'Lv': 100},
    {'Name': 'Excadrill', 'Gender': None, 'Item': 'Focus Sash', 'Ability': 'Mold Breaker', 'Shiny': None, 'HP': None,
     'Atk': '252', 'Def': '4', 'SpA': None, 'SpD': None, 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Jolly', 'Move1': 'Stealth Rock', 'Move2': 'Rapid Spin',
     'Move3': 'Earthquake', 'Move4': 'Rock Tomb', 'Lv': 100}], 'Ferrothorn': [
    {'Name': 'Ferrothorn', 'Gender': None, 'Item': 'Leftovers', 'Ability': 'Iron Barbs', 'Shiny': None, 'HP': '252',
     'Atk': None, 'Def': '24', 'SpA': None, 'SpD': '232', 'Spe': None, 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': '0', 'Nature': 'Sassy', 'Move1': 'Spikes', 'Move2': 'Leech Seed',
     'Move3': 'Gyro Ball', 'Move4': 'Power Whip', 'Lv': 100}], 'Garchomp': [
    {'Name': 'Garchomp', 'Gender': None, 'Item': 'Rockium Z', 'Ability': 'Rough Skin', 'Shiny': None, 'HP': None,
     'Atk': '252', 'Def': None, 'SpA': None, 'SpD': '4', 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Jolly', 'Move1': 'Stealth Rock', 'Move2': 'Earthquake',
     'Move3': 'Stone Edge', 'Move4': 'Swords Dance', 'Lv': 100},
    {'Name': 'Garchomp', 'Gender': None, 'Item': 'Rocky Helmet', 'Ability': 'Rough Skin', 'Shiny': None, 'HP': '252',
     'Atk': None, 'Def': '4', 'SpA': None, 'SpD': None, 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Jolly', 'Move1': 'Stealth Rock', 'Move2': 'Earthquake',
     'Move3': 'Fire Blast', 'Move4': 'Toxic', 'Lv': 100},
    {'Name': 'Garchomp', 'Gender': None, 'Item': 'Garchompite', 'Ability': 'Rough Skin', 'Shiny': None, 'HP': None,
     'Atk': '4', 'Def': None, 'SpA': '252', 'SpD': None, 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Mild', 'Move1': 'Stealth Rock', 'Move2': 'Earthquake',
     'Move3': 'Draco Meteor', 'Move4': 'Fire Blast', 'Lv': 100},
    {'Name': 'Garchomp', 'Gender': None, 'Item': 'Garchompite', 'Ability': 'Rough Skin', 'Shiny': None, 'HP': None,
     'Atk': '252', 'Def': None, 'SpA': None, 'SpD': '4', 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Jolly', 'Move1': 'Swords Dance', 'Move2': 'Earthquake',
     'Move3': 'Stone Edge', 'Move4': 'Substitute', 'Lv': 100}], 'Gliscor': [
    {'Name': 'Gliscor', 'Gender': None, 'Item': 'Toxic Orb', 'Ability': 'Poison Heal', 'Shiny': None, 'HP': '244',
     'Atk': None, 'Def': None, 'SpA': None, 'SpD': '244', 'Spe': '20', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Jolly', 'Move1': 'Swords Dance', 'Move2': 'Roost',
     'Move3': 'Earthquake', 'Move4': 'Facade', 'Lv': 100},
    {'Name': 'Gliscor', 'Gender': None, 'Item': 'Toxic Orb', 'Ability': 'Poison Heal', 'Shiny': None, 'HP': '244',
     'Atk': None, 'Def': '52', 'SpA': None, 'SpD': '76', 'Spe': '136', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Jolly', 'Move1': 'Stealth Rock', 'Move2': 'Earthquake',
     'Move3': 'Toxic', 'Move4': 'Roost', 'Lv': 100},
    {'Name': 'Gliscor', 'Gender': None, 'Item': 'Toxic Orb', 'Ability': 'Poison Heal', 'Shiny': None, 'HP': '244',
     'Atk': None, 'Def': '52', 'SpA': None, 'SpD': '76', 'Spe': '136', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Jolly', 'Move1': 'Earthquake', 'Move2': 'Defog',
     'Move3': 'Roost', 'Move4': 'Knock Off', 'Lv': 100}], 'Greninja': [
    {'Name': 'Greninja', 'Gender': 'M', 'Item': 'Choice Specs', 'Ability': 'Battle Bond', 'Shiny': None, 'HP': None,
     'Atk': None, 'Def': '4', 'SpA': '252', 'SpD': None, 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Timid', 'Move1': 'Hydro Pump', 'Move2': 'Dark Pulse',
     'Move3': 'Water Shuriken', 'Move4': 'Spikes', 'Lv': 100},
    {'Name': 'Greninja', 'Gender': None, 'Item': 'Groundium Z', 'Ability': 'Protean', 'Shiny': None, 'HP': None,
     'Atk': '252', 'Def': None, 'SpA': '4', 'SpD': None, 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Hasty', 'Move1': 'Dig', 'Move2': 'Ice Beam',
     'Move3': 'Gunk Shot', 'Move4': 'Spikes', 'Lv': 100},
    {'Name': 'Greninja', 'Gender': None, 'Item': 'Waterium Z', 'Ability': 'Protean', 'Shiny': None, 'HP': None,
     'Atk': '4', 'Def': None, 'SpA': '252', 'SpD': None, 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Hasty', 'Move1': 'Hydro Pump', 'Move2': 'Gunk Shot',
     'Move3': 'Hidden Power Fire', 'Move4': 'Spikes', 'Lv': 100},
    {'Name': 'Greninja', 'Gender': None, 'Item': 'Choice Scarf', 'Ability': 'Protean', 'Shiny': None, 'HP': None,
     'Atk': '176', 'Def': None, 'SpA': '80', 'SpD': None, 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Hasty', 'Move1': 'Rock Slide', 'Move2': 'U-turn',
     'Move3': 'Ice Beam', 'Move4': 'Spikes', 'Lv': 100},
    {'Name': 'Greninja', 'Gender': None, 'Item': 'Focus Sash', 'Ability': 'Protean', 'Shiny': None, 'HP': None,
     'Atk': None, 'Def': None, 'SpA': '252', 'SpD': '4', 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Timid', 'Move1': 'Spikes', 'Move2': 'Toxic Spikes',
     'Move3': 'Taunt', 'Move4': 'Ice Beam', 'Lv': 100}], 'Gyarados': [
    {'Name': 'Gyarados', 'Gender': None, 'Item': 'Flyinium Z', 'Ability': 'Moxie', 'Shiny': None, 'HP': None,
     'Atk': '252', 'Def': None, 'SpA': None, 'SpD': '4', 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Jolly', 'Move1': 'Dragon Dance', 'Move2': 'Bounce',
     'Move3': 'Waterfall', 'Move4': 'Earthquake', 'Lv': 100},
    {'Name': 'Gyarados', 'Gender': None, 'Item': 'Gyaradosite', 'Ability': 'Intimidate', 'Shiny': None, 'HP': None,
     'Atk': '252', 'Def': None, 'SpA': None, 'SpD': '4', 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Jolly', 'Move1': 'Dragon Dance', 'Move2': 'Crunch',
     'Move3': 'Earthquake', 'Move4': 'Substitute', 'Lv': 100}], 'Hawlucha': [
    {'Name': 'Hawlucha', 'Gender': None, 'Item': 'Electric Seed', 'Ability': 'Unburden', 'Shiny': None, 'HP': '96',
     'Atk': '252', 'Def': None, 'SpA': None, 'SpD': '36', 'Spe': '124', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Adamant', 'Move1': 'Acrobatics', 'Move2': 'Swords Dance',
     'Move3': 'High Jump Kick', 'Move4': 'Roost', 'Lv': 100}], 'Heatran': [
    {'Name': 'Heatran', 'Gender': None, 'Item': 'Leftovers', 'Ability': 'Flash Fire', 'Shiny': None, 'HP': '252',
     'Atk': None, 'Def': None, 'SpA': None, 'SpD': '180', 'Spe': '76', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Calm', 'Move1': 'Magma Storm', 'Move2': 'Earth Power',
     'Move3': 'Toxic', 'Move4': 'Stealth Rock', 'Lv': 100},
    {'Name': 'Heatran', 'Gender': None, 'Item': 'Steelium Z', 'Ability': 'Flash Fire', 'Shiny': None, 'HP': None,
     'Atk': None, 'Def': '4', 'SpA': '252', 'SpD': None, 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Modest', 'Move1': 'Magma Storm', 'Move2': 'Earth Power',
     'Move3': 'Flash Cannon', 'Move4': 'Stealth Rock', 'Lv': 100}], 'Jirachi': [
    {'Name': 'Jirachi', 'Gender': None, 'Item': 'Choice Scarf', 'Ability': 'Serene Grace', 'Shiny': None, 'HP': None,
     'Atk': '252', 'Def': None, 'SpA': None, 'SpD': '4', 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Jolly', 'Move1': 'Iron Head', 'Move2': 'U-turn',
     'Move3': 'Healing Wish', 'Move4': 'Fire Punch', 'Lv': 100},
    {'Name': 'Jirachi', 'Gender': None, 'Item': 'Leftovers', 'Ability': 'Serene Grace', 'Shiny': None, 'HP': '248',
     'Atk': None, 'Def': None, 'SpA': None, 'SpD': '188', 'Spe': '72', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Careful', 'Move1': 'Wish', 'Move2': 'Protect',
     'Move3': 'Iron Head', 'Move4': 'U-turn', 'Lv': 100},
    {'Name': 'Jirachi', 'Gender': None, 'Item': 'Leftovers', 'Ability': 'Serene Grace', 'Shiny': None, 'HP': '248',
     'Atk': None, 'Def': None, 'SpA': None, 'SpD': '188', 'Spe': '72', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Careful', 'Move1': 'Stealth Rock', 'Move2': 'Iron Head',
     'Move3': 'U-turn', 'Move4': 'Healing Wish', 'Lv': 100}], 'Kartana': [
    {'Name': 'Kartana', 'Gender': None, 'Item': 'Normalium Z', 'Ability': 'Beast Boost', 'Shiny': None, 'HP': None,
     'Atk': '252', 'Def': None, 'SpA': None, 'SpD': '4', 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Jolly', 'Move1': 'Swords Dance', 'Move2': 'Leaf Blade',
     'Move3': 'Sacred Sword', 'Move4': 'Giga Impact', 'Lv': 100},
    {'Name': 'Kartana', 'Gender': None, 'Item': 'Choice Scarf', 'Ability': 'Beast Boost', 'Shiny': None, 'HP': None,
     'Atk': '252', 'Def': None, 'SpA': None, 'SpD': '4', 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Jolly', 'Move1': 'Leaf Blade', 'Move2': 'Sacred Sword',
     'Move3': 'Smart Strike', 'Move4': 'Knock Off', 'Lv': 100},
    {'Name': 'Kartana', 'Gender': None, 'Item': 'Choice Band', 'Ability': 'Beast Boost', 'Shiny': None, 'HP': None,
     'Atk': '252', 'Def': None, 'SpA': None, 'SpD': '4', 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Jolly', 'Move1': 'Leaf Blade', 'Move2': 'Knock Off',
     'Move3': 'Sacred Sword', 'Move4': 'Smart Strike', 'Lv': 100}], 'Keldeo': [
    {'Name': 'Keldeo', 'Gender': None, 'Item': 'Leftovers', 'Ability': 'Justified', 'Shiny': None, 'HP': None,
     'Atk': None, 'Def': None, 'SpA': '252', 'SpD': '4', 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Timid', 'Move1': 'Calm Mind', 'Move2': 'Scald',
     'Move3': 'Secret Sword', 'Move4': 'Substitute', 'Lv': 100}], 'Kommo-o': [
    {'Name': 'Kommo-o', 'Gender': None, 'Item': 'Kommonium Z', 'Ability': 'Bulletproof', 'Shiny': None, 'HP': '4',
     'Atk': '252', 'Def': None, 'SpA': None, 'SpD': None, 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Hasty', 'Move1': 'Stealth Rock', 'Move2': 'Clanging Scales',
     'Move3': 'Close Combat', 'Move4': 'Poison Jab', 'Lv': 100},
    {'Name': 'Kommo-o', 'Gender': None, 'Item': 'Leftovers', 'Ability': 'Bulletproof', 'Shiny': None, 'HP': '252',
     'Atk': None, 'Def': None, 'SpA': None, 'SpD': '116', 'Spe': '140', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Careful', 'Move1': 'Stealth Rock', 'Move2': 'Toxic',
     'Move3': 'Protect', 'Move4': 'Drain Punch', 'Lv': 100},
    {'Name': 'Kommo-o', 'Gender': None, 'Item': 'Salac Berry', 'Ability': 'Bulletproof', 'Shiny': None, 'HP': '52',
     'Atk': '204', 'Def': None, 'SpA': None, 'SpD': None, 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Jolly', 'Move1': 'Belly Drum', 'Move2': 'Substitute',
     'Move3': 'Drain Punch', 'Move4': 'Thunder Punch', 'Lv': 100}], 'Kyurem-Black': [
    {'Name': 'Kyurem-Black', 'Gender': None, 'Item': 'Icium Z', 'Ability': 'Teravolt', 'Shiny': None, 'HP': None,
     'Atk': '252', 'Def': None, 'SpA': '4', 'SpD': None, 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Naive', 'Move1': 'Freeze Shock', 'Move2': 'Fusion Bolt',
     'Move3': 'Ice Beam', 'Move4': 'Earth Power', 'Lv': 100},
    {'Name': 'Kyurem-Black', 'Gender': None, 'Item': 'Life Orb', 'Ability': 'Teravolt', 'Shiny': None, 'HP': None,
     'Atk': '4', 'Def': None, 'SpA': '252', 'SpD': None, 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Naive', 'Move1': 'Ice Beam', 'Move2': 'Fusion Bolt',
     'Move3': 'Roost', 'Move4': 'Hidden Power Fire', 'Lv': 100}], 'Landorus-Therian': [
    {'Name': 'Landorus-Therian', 'Gender': None, 'Item': 'Choice Scarf', 'Ability': 'Intimidate', 'Shiny': None,
     'HP': None, 'Atk': '232', 'Def': '68', 'SpA': None, 'SpD': None, 'Spe': '208', 'iHP': None, 'iAtk': None,
     'iDef': None, 'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Jolly', 'Move1': 'Earthquake',
     'Move2': 'U-turn', 'Move3': 'Stone Edge', 'Move4': 'Defog', 'Lv': 100},
    {'Name': 'Landorus-Therian', 'Gender': None, 'Item': 'Flyinium Z', 'Ability': 'Intimidate', 'Shiny': None,
     'HP': None, 'Atk': '252', 'Def': '4', 'SpA': None, 'SpD': None, 'Spe': '252', 'iHP': None, 'iAtk': None,
     'iDef': None, 'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Jolly', 'Move1': 'Stealth Rock',
     'Move2': 'Swords Dance', 'Move3': 'Earthquake', 'Move4': 'Fly', 'Lv': 100},
    {'Name': 'Landorus-Therian', 'Gender': None, 'Item': 'Rocky Helmet', 'Ability': 'Intimidate', 'Shiny': None,
     'HP': '252', 'Atk': None, 'Def': '112', 'SpA': None, 'SpD': None, 'Spe': '144', 'iHP': None, 'iAtk': None,
     'iDef': None, 'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Impish', 'Move1': 'Stealth Rock',
     'Move2': 'Earthquake', 'Move3': 'Hidden Power Ice', 'Move4': 'U-turn', 'Lv': 100},
    {'Name': 'Landorus-Therian', 'Gender': None, 'Item': 'Focus Sash', 'Ability': 'Intimidate', 'Shiny': None,
     'HP': None, 'Atk': '252', 'Def': None, 'SpA': None, 'SpD': '4', 'Spe': '252', 'iHP': None, 'iAtk': None,
     'iDef': None, 'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Jolly', 'Move1': 'Stealth Rock',
     'Move2': 'Earthquake', 'Move3': 'Explosion', 'Move4': 'Rock Tomb', 'Lv': 100}], 'Latias': [
    {'Name': 'Latias', 'Gender': None, 'Item': 'Latiasite', 'Ability': 'Levitate', 'Shiny': None, 'HP': '248',
     'Atk': None, 'Def': '8', 'SpA': None, 'SpD': None, 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Timid', 'Move1': 'Ice Beam', 'Move2': 'Hidden Power Ground',
     'Move3': 'Thunder Wave', 'Move4': 'Roost', 'Lv': 100},
    {'Name': 'Latias', 'Gender': None, 'Item': 'Latiasite', 'Ability': 'Levitate', 'Shiny': None, 'HP': '248',
     'Atk': None, 'Def': '8', 'SpA': None, 'SpD': None, 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Timid', 'Move1': 'Calm Mind', 'Move2': 'Stored Power',
     'Move3': 'Ice Beam', 'Move4': 'Roost', 'Lv': 100}], 'Lopunny': [
    {'Name': 'Lopunny', 'Gender': None, 'Item': 'Lopunnite', 'Ability': 'Limber', 'Shiny': None, 'HP': None,
     'Atk': '252', 'Def': None, 'SpA': None, 'SpD': '4', 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Jolly', 'Move1': 'Return', 'Move2': 'High Jump Kick',
     'Move3': 'Fake Out', 'Move4': 'Ice Punch', 'Lv': 100}], 'Magearna': [
    {'Name': 'Magearna', 'Gender': None, 'Item': 'Electrium Z', 'Ability': 'Soul-Heart', 'Shiny': None, 'HP': None,
     'Atk': None, 'Def': None, 'SpA': '252', 'SpD': '4', 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Timid', 'Move1': 'Shift Gear', 'Move2': 'Thunderbolt',
     'Move3': 'Ice Beam', 'Move4': 'Focus Blast', 'Lv': 100},
    {'Name': 'Magearna', 'Gender': None, 'Item': 'Leftovers', 'Ability': 'Soul-Heart', 'Shiny': None, 'HP': '248',
     'Atk': None, 'Def': '28', 'SpA': None, 'SpD': '232', 'Spe': None, 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': '6', 'Nature': 'Calm', 'Move1': 'Heart Swap', 'Move2': 'Pain Split',
     'Move3': 'Volt Switch', 'Move4': 'Flash Cannon', 'Lv': 100},
    {'Name': 'Magearna', 'Gender': None, 'Item': 'Assault Vest', 'Ability': 'Soul-Heart', 'Shiny': None, 'HP': '248',
     'Atk': None, 'Def': None, 'SpA': None, 'SpD': '224', 'Spe': '36', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Sassy', 'Move1': 'Volt Switch', 'Move2': 'Fleur Cannon',
     'Move3': 'Focus Blast', 'Move4': 'Iron Head', 'Lv': 100},
    {'Name': 'Magearna', 'Gender': None, 'Item': 'Fairium Z', 'Ability': 'Soul-Heart', 'Shiny': None, 'HP': '248',
     'Atk': None, 'Def': '28', 'SpA': '224', 'SpD': '8', 'Spe': None, 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Modest', 'Move1': 'Calm Mind', 'Move2': 'Pain Split',
     'Move3': 'Fleur Cannon', 'Move4': 'Thunderbolt', 'Lv': 100}], 'Magnezone': [
    {'Name': 'Magnezone', 'Gender': None, 'Item': 'Electrium Z', 'Ability': 'Magnet Pull', 'Shiny': None, 'HP': None,
     'Atk': None, 'Def': '4', 'SpA': '252', 'SpD': None, 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Modest', 'Move1': 'Substitute', 'Move2': 'Thunderbolt',
     'Move3': 'Flash Cannon', 'Move4': 'Hidden Power Fire', 'Lv': 100},
    {'Name': 'Magnezone', 'Gender': None, 'Item': 'Choice Scarf', 'Ability': 'Magnet Pull', 'Shiny': None, 'HP': '4',
     'Atk': None, 'Def': '4', 'SpA': '248', 'SpD': None, 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Timid', 'Move1': 'Thunderbolt', 'Move2': 'Hidden Power Fire',
     'Move3': 'Flash Cannon', 'Move4': 'Volt Switch', 'Lv': 100},
    {'Name': 'Magnezone', 'Gender': None, 'Item': 'Choice Specs', 'Ability': 'Magnet Pull', 'Shiny': None, 'HP': '4',
     'Atk': None, 'Def': None, 'SpA': '252', 'SpD': None, 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Modest', 'Move1': 'Thunderbolt', 'Move2': 'Hidden Power Fire',
     'Move3': 'Flash Cannon', 'Move4': 'Volt Switch', 'Lv': 100},
    {'Name': 'Magnezone', 'Gender': None, 'Item': 'Electrium Z', 'Ability': 'Magnet Pull', 'Shiny': None, 'HP': None,
     'Atk': None, 'Def': '4', 'SpA': '252', 'SpD': None, 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Modest', 'Move1': 'Substitute', 'Move2': 'Thunderbolt',
     'Move3': 'Flash Cannon', 'Move4': 'Hidden Power Fire', 'Lv': 100},
    {'Name': 'Magnezone', 'Gender': None, 'Item': 'Choice Scarf', 'Ability': 'Magnet Pull', 'Shiny': None, 'HP': '4',
     'Atk': None, 'Def': '4', 'SpA': '248', 'SpD': None, 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Timid', 'Move1': 'Thunderbolt', 'Move2': 'Hidden Power Fire',
     'Move3': 'Flash Cannon', 'Move4': 'Volt Switch', 'Lv': 100},
    {'Name': 'Magnezone', 'Gender': None, 'Item': 'Choice Specs', 'Ability': 'Magnet Pull', 'Shiny': None, 'HP': '4',
     'Atk': None, 'Def': None, 'SpA': '252', 'SpD': None, 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Modest', 'Move1': 'Thunderbolt', 'Move2': 'Hidden Power Fire',
     'Move3': 'Flash Cannon', 'Move4': 'Volt Switch', 'Lv': 100}], 'Manaphy': [
    {'Name': 'Manaphy', 'Gender': None, 'Item': 'Waterium Z', 'Ability': 'Hydration', 'Shiny': None, 'HP': '248',
     'Atk': None, 'Def': None, 'SpA': '240', 'SpD': None, 'Spe': '20', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Modest', 'Move1': 'Tail Glow', 'Move2': 'Rest',
     'Move3': 'Surf', 'Move4': 'Ice Beam', 'Lv': 100},
    {'Name': 'Manaphy', 'Gender': None, 'Item': 'Waterium Z', 'Ability': 'Hydration', 'Shiny': None, 'HP': None,
     'Atk': None, 'Def': None, 'SpA': '252', 'SpD': '4', 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Timid', 'Move1': 'Tail Glow', 'Move2': 'Surf',
     'Move3': 'Ice Beam', 'Move4': 'Psychic', 'Lv': 100}], 'Mawile': [
    {'Name': 'Mawile', 'Gender': None, 'Item': 'Mawilite', 'Ability': 'Intimidate', 'Shiny': None, 'HP': '92',
     'Atk': '252', 'Def': None, 'SpA': None, 'SpD': None, 'Spe': '164', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Adamant', 'Move1': 'Swords Dance', 'Move2': 'Play Rough',
     'Move3': 'Sucker Punch', 'Move4': 'Knock Off', 'Lv': 100},
    {'Name': 'Mawile', 'Gender': None, 'Item': 'Mawilite', 'Ability': 'Intimidate', 'Shiny': None, 'HP': '92',
     'Atk': '252', 'Def': None, 'SpA': None, 'SpD': None, 'Spe': '164', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Adamant', 'Move1': 'Play Rough', 'Move2': 'Thunder Punch',
     'Move3': 'Sucker Punch', 'Move4': 'Brick Break', 'Lv': 100},
    {'Name': 'Mawile', 'Gender': None, 'Item': 'Mawilite', 'Ability': 'Intimidate', 'Shiny': None, 'HP': '144',
     'Atk': '252', 'Def': None, 'SpA': None, 'SpD': None, 'Spe': '112', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Adamant', 'Move1': 'Substitute', 'Move2': 'Thunder Punch',
     'Move3': 'Ice Punch', 'Move4': 'Focus Punch', 'Lv': 100}], 'Medicham': [
    {'Name': 'Medicham', 'Gender': None, 'Item': 'Medichamite', 'Ability': 'Telepathy', 'Shiny': None, 'HP': None,
     'Atk': '252', 'Def': '4', 'SpA': None, 'SpD': None, 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Jolly', 'Move1': 'Fake Out', 'Move2': 'High Jump Kick',
     'Move3': 'Ice Punch', 'Move4': 'Zen Headbutt', 'Lv': 100}], 'Pelipper': [
    {'Name': 'Pelipper', 'Gender': None, 'Item': 'Damp Rock', 'Ability': 'Drizzle', 'Shiny': None, 'HP': '248',
     'Atk': None, 'Def': '36', 'SpA': None, 'SpD': '224', 'Spe': None, 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Bold', 'Move1': 'Scald', 'Move2': 'U-turn', 'Move3': 'Roost',
     'Move4': 'Defog', 'Lv': 100},
    {'Name': 'Pelipper', 'Gender': None, 'Item': 'Choice Specs', 'Ability': 'Drizzle', 'Shiny': None, 'HP': None,
     'Atk': None, 'Def': None, 'SpA': '252', 'SpD': '4', 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Modest', 'Move1': 'Hydro Pump', 'Move2': 'Hurricane',
     'Move3': 'Surf', 'Move4': 'U-turn', 'Lv': 100}], 'Rotom-Wash': [
    {'Name': 'Rotom-Wash', 'Gender': None, 'Item': 'Electrium Z', 'Ability': 'Levitate', 'Shiny': None, 'HP': '108',
     'Atk': None, 'Def': None, 'SpA': '184', 'SpD': None, 'Spe': '216', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Timid', 'Move1': 'Hydro Pump', 'Move2': 'Volt Switch',
     'Move3': 'Thunder', 'Move4': 'Pain Split', 'Lv': 100},
    {'Name': 'Rotom-Wash', 'Gender': None, 'Item': 'Wiki Berry', 'Ability': 'Levitate', 'Shiny': None, 'HP': '252',
     'Atk': None, 'Def': '252', 'SpA': None, 'SpD': '4', 'Spe': None, 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Bold', 'Move1': 'Volt Switch', 'Move2': 'Hydro Pump',
     'Move3': 'Defog', 'Move4': 'Pain Split', 'Lv': 100}], 'Sableye': [
    {'Name': 'Sableye', 'Gender': None, 'Item': 'Sablenite', 'Ability': 'Prankster', 'Shiny': None, 'HP': '248',
     'Atk': None, 'Def': '8', 'SpA': None, 'SpD': '252', 'Spe': None, 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Careful', 'Move1': 'Knock Off', 'Move2': 'Will-O-Wisp',
     'Move3': 'Recover', 'Move4': 'Protect', 'Lv': 100}], 'Scizor': [
    {'Name': 'Scizor', 'Gender': None, 'Item': 'Scizorite', 'Ability': 'Light Metal', 'Shiny': None, 'HP': '248',
     'Atk': None, 'Def': '16', 'SpA': None, 'SpD': '244', 'Spe': None, 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Impish', 'Move1': 'Swords Dance', 'Move2': 'Bullet Punch',
     'Move3': 'Roost', 'Move4': 'Knock Off', 'Lv': 100}], 'Serperior': [
    {'Name': 'Serperior', 'Gender': None, 'Item': 'Leftovers', 'Ability': 'Contrary', 'Shiny': None, 'HP': '56',
     'Atk': None, 'Def': None, 'SpA': '200', 'SpD': None, 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Timid', 'Move1': 'Leaf Storm', 'Move2': 'Hidden Power Fire',
     'Move3': 'Substitute', 'Move4': 'Glare', 'Lv': 100},
    {'Name': 'Serperior', 'Gender': None, 'Item': 'Choice Scarf', 'Ability': 'Contrary', 'Shiny': None, 'HP': None,
     'Atk': None, 'Def': None, 'SpA': '252', 'SpD': '4', 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Timid', 'Move1': 'Leaf Storm', 'Move2': 'Glare',
     'Move3': 'Defog', 'Move4': 'Knock Off', 'Lv': 100}], 'Skarmory': [
    {'Name': 'Skarmory', 'Gender': None, 'Item': 'Rocky Helmet', 'Ability': 'Sturdy', 'Shiny': None, 'HP': '252',
     'Atk': None, 'Def': '252', 'SpA': None, 'SpD': '4', 'Spe': None, 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Bold', 'Move1': 'Roost', 'Move2': 'Spikes',
     'Move3': 'Whirlwind', 'Move4': 'Counter', 'Lv': 100}], 'Swampert': [
    {'Name': 'Swampert', 'Gender': None, 'Item': 'Swampertite', 'Ability': 'Damp', 'Shiny': None, 'HP': None,
     'Atk': '252', 'Def': '4', 'SpA': None, 'SpD': None, 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Jolly', 'Move1': 'Waterfall', 'Move2': 'Earthquake',
     'Move3': 'Ice Punch', 'Move4': 'Stealth Rock', 'Lv': 100}], 'Tangrowth': [
    {'Name': 'Tangrowth', 'Gender': None, 'Item': 'Assault Vest', 'Ability': 'Regenerator', 'Shiny': None, 'HP': '252',
     'Atk': None, 'Def': '12', 'SpA': None, 'SpD': '244', 'Spe': None, 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Sassy', 'Move1': 'Giga Drain', 'Move2': 'Knock Off',
     'Move3': 'Hidden Power Ice', 'Move4': 'Earthquake', 'Lv': 100},
    {'Name': 'Tangrowth', 'Gender': None, 'Item': 'Rocky Helmet', 'Ability': 'Regenerator', 'Shiny': None, 'HP': '252',
     'Atk': None, 'Def': '168', 'SpA': None, 'SpD': '88', 'Spe': None, 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Relaxed', 'Move1': 'Giga Drain', 'Move2': 'Knock Off',
     'Move3': 'Hidden Power Ice', 'Move4': 'Sludge Bomb', 'Lv': 100}], 'Tapu Bulu': [
    {'Name': 'Tapu Bulu', 'Gender': None, 'Item': 'Choice Band', 'Ability': 'Grassy Surge', 'Shiny': None, 'HP': '84',
     'Atk': '248', 'Def': None, 'SpA': None, 'SpD': None, 'Spe': '176', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Adamant', 'Move1': 'Wood Hammer', 'Move2': 'Horn Leech',
     'Move3': 'Superpower', 'Move4': 'Stone Edge', 'Lv': 100},
    {'Name': 'Tapu Bulu', 'Gender': None, 'Item': 'Leftovers', 'Ability': 'Grassy Surge', 'Shiny': None, 'HP': '248',
     'Atk': None, 'Def': '8', 'SpA': None, 'SpD': '252', 'Spe': None, 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Careful', 'Move1': 'Swords Dance', 'Move2': 'Horn Leech',
     'Move3': 'Superpower', 'Move4': 'Synthesis', 'Lv': 100},
    {'Name': 'Tapu Bulu', 'Gender': None, 'Item': 'Fightinium Z', 'Ability': 'Grassy Surge', 'Shiny': None, 'HP': '236',
     'Atk': '144', 'Def': None, 'SpA': None, 'SpD': '32', 'Spe': '96', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Adamant', 'Move1': 'Swords Dance', 'Move2': 'Horn Leech',
     'Move3': 'Superpower', 'Move4': 'Stone Edge', 'Lv': 100},
    {'Name': 'Tapu Bulu', 'Gender': None, 'Item': 'Choice Scarf', 'Ability': 'Grassy Surge', 'Shiny': None, 'HP': None,
     'Atk': '252', 'Def': None, 'SpA': None, 'SpD': '4', 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Jolly', 'Move1': 'Horn Leech', 'Move2': 'Wood Hammer',
     'Move3': 'Superpower', 'Move4': 'Stone Edge', 'Lv': 100}], 'Tapu Fini': [
    {'Name': 'Tapu Fini', 'Gender': None, 'Item': 'Leftovers', 'Ability': 'Misty Surge', 'Shiny': None, 'HP': '248',
     'Atk': None, 'Def': '16', 'SpA': '12', 'SpD': '40', 'Spe': '192', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Calm', 'Move1': 'Defog', 'Move2': 'Moonblast',
     'Move3': 'Scald', 'Move4': 'Taunt', 'Lv': 100}], 'Tapu Koko': [
    {'Name': 'Tapu Koko', 'Gender': None, 'Item': 'Choice Specs', 'Ability': 'Electric Surge', 'Shiny': None,
     'HP': None, 'Atk': None, 'Def': None, 'SpA': '252', 'SpD': '4', 'Spe': '252', 'iHP': None, 'iAtk': None,
     'iDef': None, 'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Timid', 'Move1': 'Thunderbolt',
     'Move2': 'Dazzling Gleam', 'Move3': 'Volt Switch', 'Move4': 'Hidden Power Ice', 'Lv': 100},
    {'Name': 'Tapu Koko', 'Gender': None, 'Item': 'Electrium Z', 'Ability': 'Electric Surge', 'Shiny': None, 'HP': None,
     'Atk': '252', 'Def': None, 'SpA': '4', 'SpD': None, 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Hasty', 'Move1': 'Wild Charge', 'Move2': 'Hidden Power Ice',
     'Move3': 'U-turn', 'Move4': 'Roost', 'Lv': 100},
    {'Name': 'Tapu Koko', 'Gender': None, 'Item': 'Shuca Berry', 'Ability': 'Electric Surge', 'Shiny': None, 'HP': None,
     'Atk': None, 'Def': None, 'SpA': '252', 'SpD': '4', 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Timid', 'Move1': 'Thunderbolt', 'Move2': 'Hidden Power Ice',
     'Move3': 'U-turn', 'Move4': 'Roost', 'Lv': 100}], 'Tapu Lele': [
    {'Name': 'Tapu Lele', 'Gender': None, 'Item': 'Choice Specs', 'Ability': 'Psychic Surge', 'Shiny': None, 'HP': None,
     'Atk': None, 'Def': None, 'SpA': '252', 'SpD': '4', 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Timid', 'Move1': 'Psychic', 'Move2': 'Moonblast',
     'Move3': 'Psyshock', 'Move4': 'Hidden Power Fire', 'Lv': 100},
    {'Name': 'Tapu Lele', 'Gender': None, 'Item': 'Fightinium Z', 'Ability': 'Psychic Surge', 'Shiny': None, 'HP': None,
     'Atk': None, 'Def': None, 'SpA': '252', 'SpD': '4', 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Timid', 'Move1': 'Psychic', 'Move2': 'Moonblast',
     'Move3': 'Focus Blast', 'Move4': 'Calm Mind', 'Lv': 100},
    {'Name': 'Tapu Lele', 'Gender': None, 'Item': 'Choice Scarf', 'Ability': 'Psychic Surge', 'Shiny': None, 'HP': None,
     'Atk': None, 'Def': None, 'SpA': '252', 'SpD': '4', 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Timid', 'Move1': 'Psychic', 'Move2': 'Moonblast',
     'Move3': 'Hidden Power Fire', 'Move4': 'Focus Blast', 'Lv': 100}], 'Tornadus-Therian': [
    {'Name': 'Tornadus-Therian', 'Gender': None, 'Item': 'Rocky Helmet', 'Ability': 'Regenerator', 'Shiny': None,
     'HP': '252', 'Atk': None, 'Def': '4', 'SpA': None, 'SpD': None, 'Spe': '252', 'iHP': None, 'iAtk': None,
     'iDef': None, 'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Timid', 'Move1': 'Hurricane',
     'Move2': 'Knock Off', 'Move3': 'U-turn', 'Move4': 'Defog', 'Lv': 100},
    {'Name': 'Tornadus-Therian', 'Gender': None, 'Item': 'Flyinium Z', 'Ability': 'Regenerator', 'Shiny': None,
     'HP': '4', 'Atk': None, 'Def': None, 'SpA': '252', 'SpD': None, 'Spe': '252', 'iHP': None, 'iAtk': None,
     'iDef': None, 'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Timid', 'Move1': 'Hurricane',
     'Move2': 'Knock Off', 'Move3': 'U-turn', 'Move4': 'Defog', 'Lv': 100}], 'Toxapex': [
    {'Name': 'Toxapex', 'Gender': None, 'Item': 'Black Sludge', 'Ability': 'Regenerator', 'Shiny': None, 'HP': '252',
     'Atk': None, 'Def': '4', 'SpA': None, 'SpD': '252', 'Spe': None, 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Calm', 'Move1': 'Scald', 'Move2': 'Haze', 'Move3': 'Recover',
     'Move4': 'Toxic', 'Lv': 100}], 'Tyranitar': [
    {'Name': 'Tyranitar', 'Gender': None, 'Item': 'Tyranitarite', 'Ability': 'Sand Stream', 'Shiny': None, 'HP': '132',
     'Atk': '252', 'Def': None, 'SpA': None, 'SpD': None, 'Spe': '124', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Adamant', 'Move1': 'Stealth Rock', 'Move2': 'Stone Edge',
     'Move3': 'Pursuit', 'Move4': 'Fire Punch', 'Lv': 100},
    {'Name': 'Tyranitar', 'Gender': None, 'Item': 'Assault Vest', 'Ability': 'Sand Stream', 'Shiny': None, 'HP': '224',
     'Atk': '32', 'Def': None, 'SpA': None, 'SpD': '252', 'Spe': None, 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Careful', 'Move1': 'Rock Slide', 'Move2': 'Crunch',
     'Move3': 'Pursuit', 'Move4': 'Earthquake', 'Lv': 100},
    {'Name': 'Tyranitar', 'Gender': None, 'Item': 'Choice Band', 'Ability': 'Sand Stream', 'Shiny': None, 'HP': '40',
     'Atk': '252', 'Def': None, 'SpA': None, 'SpD': '48', 'Spe': '168', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Adamant', 'Move1': 'Stone Edge', 'Move2': 'Crunch',
     'Move3': 'Pursuit', 'Move4': 'Earthquake', 'Lv': 100},
    {'Name': 'Tyranitar', 'Gender': None, 'Item': 'Tyranitarite', 'Ability': 'Sand Stream', 'Shiny': None, 'HP': None,
     'Atk': '252', 'Def': None, 'SpA': None, 'SpD': '4', 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Jolly', 'Move1': 'Dragon Dance', 'Move2': 'Stone Edge',
     'Move3': 'Ice Punch', 'Move4': 'Fire Punch', 'Lv': 100}], 'Victini': [
    {'Name': 'Victini', 'Gender': None, 'Item': 'Choice Scarf', 'Ability': 'Victory Star', 'Shiny': None, 'HP': '252',
     'Atk': '4', 'Def': None, 'SpA': None, 'SpD': None, 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Jolly', 'Move1': 'V-create', 'Move2': 'U-turn',
     'Move3': 'Final Gambit', 'Move4': 'Trick', 'Lv': 100},
    {'Name': 'Victini', 'Gender': None, 'Item': 'Choice Band', 'Ability': 'Victory Star', 'Shiny': None, 'HP': None,
     'Atk': '252', 'Def': None, 'SpA': None, 'SpD': '4', 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Jolly', 'Move1': 'V-create', 'Move2': 'Bolt Strike',
     'Move3': 'U-turn', 'Move4': 'Zen Headbutt', 'Lv': 100},
    {'Name': 'Victini', 'Gender': None, 'Item': 'Normalium Z', 'Ability': 'Victory Star', 'Shiny': None, 'HP': None,
     'Atk': None, 'Def': None, 'SpA': '252', 'SpD': '4', 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Timid', 'Move1': 'Celebrate', 'Move2': 'Searing Shot',
     'Move3': 'Stored Power', 'Move4': 'Focus Blast', 'Lv': 100}], 'Volcarona': [
    {'Name': 'Volcarona', 'Gender': None, 'Item': 'Buginium Z', 'Ability': 'Flame Body', 'Shiny': None, 'HP': '248',
     'Atk': None, 'Def': '112', 'SpA': None, 'SpD': None, 'Spe': '148', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Timid', 'Move1': 'Quiver Dance', 'Move2': 'Flamethrower',
     'Move3': 'Bug Buzz', 'Move4': 'Roost', 'Lv': 100},
    {'Name': 'Volcarona', 'Gender': None, 'Item': 'Buginium Z', 'Ability': 'Flame Body', 'Shiny': None, 'HP': None,
     'Atk': None, 'Def': None, 'SpA': '252', 'SpD': '4', 'Spe': '252', 'iHP': None, 'iAtk': None, 'iDef': None,
     'iSpA': None, 'iSpD': None, 'iSpe': None, 'Nature': 'Timid', 'Move1': 'Quiver Dance', 'Move2': 'Fire Blast',
     'Move3': 'Bug Buzz', 'Move4': 'Hidden Power Ground', 'Lv': 100}]}
