Moveset = {
    'landorustherian': {'name': 'landorustherian', 'ability': 'Intimidate', 'item': 'Choice Scarf', 'nature': 'Impish',
                        'spread': {'hp': 252, 'atk': 0, 'def': 112, 'spa': 0, 'spd': 0, 'spe': 144},
                        'moves': {'Earthquake': 0.99, 'U-turn': 0.69, 'Stealth Rock': 0.53, 'Stone Edge': 0.42,
                                  'Defog': 0.36, 'Hidden Power Ice': 0.27, 'Swords Dance': 0.19, 'Explosion': 0.18,
                                  'Fly': 0.12, 'Knock Off': 0.09}},
    'magearna': {'name': 'magearna', 'ability': 'Soul-Heart', 'item': 'Assault Vest', 'nature': 'Timid',
                 'spread': {'hp': 0, 'atk': 0, 'def': 0, 'spa': 252, 'spd': 4, 'spe': 252},
                 'moves': {'Fleur Cannon': 0.71, 'Thunderbolt': 0.51, 'Volt Switch': 0.44, 'Focus Blast': 0.39,
                           'Ice Beam': 0.33, 'Calm Mind': 0.27, 'Flash Cannon': 0.24, 'Shift Gear': 0.23,
                           'Iron Head': 0.22, 'Hidden Power Fire': 0.21, 'Trick Room': 0.18, 'Pain Split': 0.16}},
    'greninjaash': {'name': 'greninjaash', 'ability': 'Battle Bond', 'item': 'Choice Specs', 'nature': 'Timid',
                    'spread': {'hp': 0, 'atk': 0, 'def': 0, 'spa': 252, 'spd': 4, 'spe': 252},
                    'moves': {'Dark Pulse': 1.0, 'Water Shuriken': 0.99, 'Spikes': 0.66, 'Hydro Pump': 0.63,
                              'Surf': 0.39, 'Ice Beam': 0.24}},
    'heatran': {'name': 'heatran', 'ability': 'Flash Fire', 'item': 'Leftovers', 'nature': 'Calm',
                'spread': {'hp': 252, 'atk': 0, 'def': 0, 'spa': 0, 'spd': 128, 'spe': 128},
                'moves': {'Stealth Rock': 0.72, 'Earth Power': 0.71, 'Toxic': 0.6, 'Taunt': 0.51, 'Magma Storm': 0.5,
                          'Lava Plume': 0.48, 'Protect': 0.21, 'Flash Cannon': 0.07, 'Roar': 0.06}},
    'kartana': {'name': 'kartana', 'ability': 'Beast Boost', 'item': 'Choice Scarf', 'nature': 'Jolly',
                'spread': {'hp': 0, 'atk': 252, 'def': 0, 'spa': 0, 'spd': 4, 'spe': 252},
                'moves': {'Leaf Blade': 1.0, 'Sacred Sword': 0.94, 'Smart Strike': 0.68, 'Knock Off': 0.68,
                          'Swords Dance': 0.33, 'Giga Impact': 0.19}},
    'toxapex': {'name': 'toxapex', 'ability': 'Regenerator', 'item': 'Black Sludge', 'nature': 'Calm',
                'spread': {'hp': 252, 'atk': 0, 'def': 4, 'spa': 0, 'spd': 252, 'spe': 0},
                'moves': {'Recover': 0.97, 'Scald': 0.93, 'Haze': 0.73, 'Toxic Spikes': 0.65, 'Toxic': 0.43,
                          'Knock Off': 0.17}},
    'tapukoko': {'name': 'tapukoko', 'ability': 'Electric Surge', 'item': 'Choice Specs', 'nature': 'Timid',
                 'spread': {'hp': 0, 'atk': 0, 'def': 0, 'spa': 252, 'spd': 4, 'spe': 252},
                 'moves': {'Thunderbolt': 0.79, 'Hidden Power Ice': 0.61, 'U-turn': 0.57, 'Volt Switch': 0.46,
                           'Dazzling Gleam': 0.43, 'Roost': 0.32, 'Taunt': 0.2, 'Defog': 0.13, 'Wild Charge': 0.07,
                           'Reflect': 0.07, 'Light Screen': 0.07, 'Thunder': 0.06, 'Calm Mind': 0.05}},
    'ferrothorn': {'name': 'ferrothorn', 'ability': 'Iron Barbs', 'item': 'Leftovers', 'nature': 'Sassy',
                   'spread': {'hp': 252, 'atk': 0, 'def': 24, 'spa': 0, 'spd': 232, 'spe': 0},
                   'moves': {'Leech Seed': 0.84, 'Power Whip': 0.67, 'Gyro Ball': 0.64, 'Spikes': 0.6,
                             'Stealth Rock': 0.46, 'Knock Off': 0.29, 'Protect': 0.26, 'Bulldoze': 0.11}},
    'tornadustherian': {'name': 'tornadustherian', 'ability': 'Regenerator', 'item': 'Rocky Helmet', 'nature': 'Timid',
                        'spread': {'hp': 240, 'atk': 0, 'def': 64, 'spa': 0, 'spd': 0, 'spe': 204},
                        'moves': {'Hurricane': 0.97, 'Defog': 0.82, 'U-turn': 0.7, 'Knock Off': 0.55, 'Taunt': 0.42,
                                  'Heat Wave': 0.18, 'Focus Blast': 0.13, 'Superpower': 0.12}},
    'tapulele': {'name': 'tapulele', 'ability': 'Psychic Surge', 'item': 'Choice Specs', 'nature': 'Timid',
                 'spread': {'hp': 0, 'atk': 0, 'def': 0, 'spa': 252, 'spd': 4, 'spe': 252},
                 'moves': {'Moonblast': 1.0, 'Psyshock': 0.84, 'Hidden Power Fire': 0.66, 'Psychic': 0.63,
                           'Focus Blast': 0.41, 'Calm Mind': 0.28}},
    'chansey': {'name': 'chansey', 'ability': 'Natural Cure', 'item': 'Eviolite', 'nature': 'Bold',
                'spread': {'hp': 248, 'atk': 0, 'def': 252, 'spa': 0, 'spd': 8, 'spe': 0},
                'moves': {'Seismic Toss': 1.0, 'Soft-Boiled': 0.96, 'Toxic': 0.48, 'Stealth Rock': 0.45,
                          'Thunder Wave': 0.36, 'Heal Bell': 0.26, 'Aromatherapy': 0.25, 'Wish': 0.11}},
    'skarmory': {'name': 'skarmory', 'ability': 'Sturdy', 'item': 'Rocky Helmet', 'nature': 'Impish',
                 'spread': {'hp': 248, 'atk': 0, 'def': 252, 'spa': 0, 'spd': 8, 'spe': 0},
                 'moves': {'Roost': 0.97, 'Spikes': 0.71, 'Whirlwind': 0.57, 'Defog': 0.52, 'Brave Bird': 0.5,
                           'Counter': 0.31, 'Stealth Rock': 0.19, 'Toxic': 0.16}},
    'zapdos': {'name': 'zapdos', 'ability': 'Static', 'item': 'Leftovers', 'nature': 'Bold',
               'spread': {'hp': 248, 'atk': 0, 'def': 240, 'spa': 0, 'spd': 0, 'spe': 20},
               'moves': {'Roost': 0.98, 'Heat Wave': 0.91, 'Defog': 0.78, 'Discharge': 0.7, 'Hidden Power Ice': 0.26,
                         'Volt Switch': 0.21}},
    'clefable': {'name': 'clefable', 'ability': 'Magic Guard', 'item': 'Leftovers', 'nature': 'Bold',
                 'spread': {'hp': 252, 'atk': 0, 'def': 252, 'spa': 4, 'spd': 0, 'spe': 0},
                 'moves': {'Moonblast': 0.98, 'Soft-Boiled': 0.66, 'Calm Mind': 0.54, 'Wish': 0.35, 'Protect': 0.3,
                           'Stealth Rock': 0.26, 'Flamethrower': 0.17, 'Cosmic Power': 0.14, 'Thunderbolt': 0.11,
                           'Aromatherapy': 0.1, 'Heal Bell': 0.08, 'Thunder Wave': 0.07, 'Counter': 0.06}},
    'greninja': {'name': 'greninja', 'ability': 'Protean', 'item': 'Life Orb', 'nature': 'Timid',
                 'spread': {'hp': 0, 'atk': 0, 'def': 0, 'spa': 252, 'spd': 4, 'spe': 252},
                 'moves': {'Ice Beam': 0.88, 'Spikes': 0.67, 'Hidden Power Fire': 0.56, 'Hydro Pump': 0.5,
                           'Gunk Shot': 0.36, 'U-turn': 0.32, 'Rock Slide': 0.16, 'Low Kick': 0.16, 'Extrasensory': 0.1,
                           'Toxic Spikes': 0.09, 'Taunt': 0.08}},
    'gliscor': {'name': 'gliscor', 'ability': 'Poison Heal', 'item': 'Toxic Orb', 'nature': 'Jolly',
                'spread': {'hp': 244, 'atk': 0, 'def': 0, 'spa': 0, 'spd': 152, 'spe': 112},
                'moves': {'Earthquake': 0.98, 'Roost': 0.81, 'Defog': 0.5, 'Swords Dance': 0.28, 'Taunt': 0.28,
                          'Toxic': 0.28, 'Stealth Rock': 0.27, 'Knock Off': 0.23, 'Facade': 0.16, 'Ice Fang': 0.1}},
    'mawilemega': {'name': 'mawilemega', 'ability': 'Huge Power', 'item': 'Mawilite', 'nature': 'Adamant',
                   'spread': {'hp': 92, 'atk': 252, 'def': 0, 'spa': 0, 'spd': 0, 'spe': 164},
                   'moves': {'Play Rough': 0.99, 'Sucker Punch': 0.94, 'Swords Dance': 0.81, 'Knock Off': 0.64,
                             'Thunder Punch': 0.31, 'Fire Fang': 0.17}},
    'excadrill': {'name': 'excadrill', 'ability': 'Mold Breaker', 'item': 'Leftovers', 'nature': 'Jolly',
                  'spread': {'hp': 0, 'atk': 252, 'def': 0, 'spa': 0, 'spd': 4, 'spe': 252},
                  'moves': {'Earthquake': 0.99, 'Rapid Spin': 0.94, 'Iron Head': 0.54, 'Stealth Rock': 0.53,
                            'Toxic': 0.35, 'Swords Dance': 0.27, 'Rock Slide': 0.22}},
    'garchomp': {'name': 'garchomp', 'ability': 'Rough Skin', 'item': 'Rocky Helmet', 'nature': 'Jolly',
                 'spread': {'hp': 0, 'atk': 252, 'def': 0, 'spa': 0, 'spd': 4, 'spe': 252},
                 'moves': {'Earthquake': 0.95, 'Stealth Rock': 0.8, 'Swords Dance': 0.5, 'Stone Edge': 0.43,
                           'Toxic': 0.3, 'Fire Blast': 0.24, 'Outrage': 0.24, 'Dragon Tail': 0.08, 'Poison Jab': 0.07,
                           'Fire Fang': 0.07, 'Roar': 0.06, 'Rock Slide': 0.05}},
    'medichammega': {'name': 'medichammega', 'ability': 'Pure Power', 'item': 'Medichamite', 'nature': 'Jolly',
                     'spread': {'hp': 0, 'atk': 252, 'def': 0, 'spa': 0, 'spd': 4, 'spe': 252},
                     'moves': {'High Jump Kick': 0.97, 'Fake Out': 0.92, 'Ice Punch': 0.88, 'Zen Headbutt': 0.75,
                               'Thunder Punch': 0.23, 'Bullet Punch': 0.15}},
    'tapubulu': {'name': 'tapubulu', 'ability': 'Grassy Surge', 'item': 'Leftovers', 'nature': 'Careful',
                 'spread': {'hp': 248, 'atk': 8, 'def': 0, 'spa': 0, 'spd': 252, 'spe': 0},
                 'moves': {'Horn Leech': 0.97, 'Superpower': 0.94, 'Swords Dance': 0.55, 'Protect': 0.49,
                           'Wood Hammer': 0.29, 'Stone Edge': 0.26, 'Synthesis': 0.15, 'Bulk Up': 0.13,
                           'Megahorn': 0.04}},
    'rotomwash': {'name': 'rotomwash', 'ability': 'Levitate', 'item': 'Leftovers', 'nature': 'Bold',
                  'spread': {'hp': 252, 'atk': 0, 'def': 200, 'spa': 0, 'spd': 0, 'spe': 56},
                  'moves': {'Volt Switch': 1.0, 'Hydro Pump': 0.98, 'Will-O-Wisp': 0.7, 'Defog': 0.67,
                            'Pain Split': 0.29, 'Thunder Wave': 0.16, 'Trick': 0.06}},
    'swampertmega': {'name': 'swampertmega', 'ability': 'Swift Swim', 'item': 'Swampertite', 'nature': 'Adamant',
                     'spread': {'hp': 0, 'atk': 252, 'def': 0, 'spa': 0, 'spd': 4, 'spe': 252},
                     'moves': {'Earthquake': 1.0, 'Ice Punch': 0.79, 'Waterfall': 0.75, 'Stealth Rock': 0.58,
                               'Substitute': 0.22, 'Scald': 0.17, 'Toxic': 0.12, 'Rest': 0.08, 'Sleep Talk': 0.08,
                               'Aqua Tail': 0.07}},
    'tapufini': {'name': 'tapufini', 'ability': 'Misty Surge', 'item': 'Leftovers', 'nature': 'Timid',
                 'spread': {'hp': 248, 'atk': 0, 'def': 8, 'spa': 0, 'spd': 0, 'spe': 252},
                 'moves': {'Moonblast': 0.92, 'Defog': 0.81, 'Taunt': 0.79, "Nature's Madness": 0.55, 'Scald': 0.37,
                           'Surf': 0.26, 'Whirlpool': 0.07, 'Hydro Pump': 0.07}},
    'tangrowth': {'name': 'tangrowth', 'ability': 'Regenerator', 'item': 'Assault Vest', 'nature': 'Sassy',
                  'spread': {'hp': 248, 'atk': 0, 'def': 8, 'spa': 0, 'spd': 252, 'spe': 0},
                  'moves': {'Giga Drain': 0.97, 'Knock Off': 0.89, 'Earthquake': 0.76, 'Hidden Power Ice': 0.52,
                            'Hidden Power Fire': 0.36, 'Sludge Bomb': 0.25, 'Sleep Powder': 0.11}},
    'jirachi': {'name': 'jirachi', 'ability': 'Serene Grace', 'item': 'Leftovers', 'nature': 'Careful',
                'spread': {'hp': 252, 'atk': 0, 'def': 0, 'spa': 0, 'spd': 224, 'spe': 32},
                'moves': {'Iron Head': 0.96, 'Wish': 0.74, 'Protect': 0.69, 'U-turn': 0.45, 'Body Slam': 0.37,
                          'Healing Wish': 0.18, 'Stealth Rock': 0.16, 'Fire Punch': 0.12, 'Substitute': 0.04,
                          'Psychic': 0.04, 'Calm Mind': 0.03, 'Flash Cannon': 0.03}},
    'pelipper': {'name': 'pelipper', 'ability': 'Drizzle', 'item': 'Damp Rock', 'nature': 'Bold',
                 'spread': {'hp': 248, 'atk': 0, 'def': 36, 'spa': 0, 'spd': 224, 'spe': 0},
                 'moves': {'Roost': 0.95, 'U-turn': 0.93, 'Scald': 0.9, 'Hurricane': 0.57, 'Defog': 0.48}},
    'celesteela': {'name': 'celesteela', 'ability': 'Beast Boost', 'item': 'Leftovers', 'nature': 'Sassy',
                   'spread': {'hp': 248, 'atk': 0, 'def': 28, 'spa': 0, 'spd': 232, 'spe': 0},
                   'moves': {'Heavy Slam': 0.94, 'Leech Seed': 0.9, 'Protect': 0.89, 'Flamethrower': 0.88,
                             'Earthquake': 0.11, 'Autotomize': 0.06, 'Fire Blast': 0.05}},
    'keldeo': {'name': 'keldeo', 'ability': 'Justified', 'item': 'Leftovers', 'nature': 'Timid',
               'spread': {'hp': 0, 'atk': 0, 'def': 0, 'spa': 252, 'spd': 4, 'spe': 252},
               'moves': {'Secret Sword': 0.98, 'Scald': 0.88, 'Calm Mind': 0.7, 'Substitute': 0.58, 'Hydro Pump': 0.36,
                         'Icy Wind': 0.13, 'Taunt': 0.1, 'Stone Edge': 0.08}},
    'scizormega': {'name': 'scizormega', 'ability': 'Technician', 'item': 'Scizorite', 'nature': 'Impish',
                   'spread': {'hp': 248, 'atk': 0, 'def': 244, 'spa': 0, 'spd': 16, 'spe': 0},
                   'moves': {'Bullet Punch': 1.0, 'Roost': 0.98, 'Swords Dance': 0.74, 'U-turn': 0.63,
                             'Knock Off': 0.31, 'Curse': 0.11, 'Defog': 0.11}},
    'hawlucha': {'name': 'hawlucha', 'ability': 'Unburden', 'item': 'Electric Seed', 'nature': 'Adamant',
                 'spread': {'hp': 96, 'atk': 252, 'def': 0, 'spa': 0, 'spd': 36, 'spe': 124},
                 'moves': {'Acrobatics': 1.0, 'Swords Dance': 1.0, 'High Jump Kick': 0.73, 'Drain Punch': 0.5,
                           'Stone Edge': 0.39, 'Roost': 0.24}},
    'venusaurmega': {'name': 'venusaurmega', 'ability': 'Thick Fat', 'item': 'Venusaurite', 'nature': 'Bold',
                     'spread': {'hp': 252, 'atk': 0, 'def': 252, 'spa': 4, 'spd': 0, 'spe': 0},
                     'moves': {'Synthesis': 0.99, 'Sludge Bomb': 0.96, 'Hidden Power Fire': 0.92, 'Giga Drain': 0.85,
                               'Leech Seed': 0.14}},
    'magnezone': {'name': 'magnezone', 'ability': 'Magnet Pull', 'item': 'Choice Specs', 'nature': 'Timid',
                  'spread': {'hp': 0, 'atk': 0, 'def': 0, 'spa': 252, 'spd': 4, 'spe': 252},
                  'moves': {'Flash Cannon': 0.99, 'Thunderbolt': 0.98, 'Hidden Power Fire': 0.97, 'Volt Switch': 0.65,
                            'Substitute': 0.34}},
    'sableyemega': {'name': 'sableyemega', 'ability': 'Magic Bounce', 'item': 'Sablenite', 'nature': 'Careful',
                    'spread': {'hp': 248, 'atk': 0, 'def': 8, 'spa': 0, 'spd': 252, 'spe': 0},
                    'moves': {'Recover': 1.0, 'Knock Off': 0.97, 'Will-O-Wisp': 0.93, 'Protect': 0.77, 'Toxic': 0.22}},
    'victini': {'name': 'victini', 'ability': 'Victory Star', 'item': 'Choice Scarf', 'nature': 'Jolly',
                'spread': {'hp': 0, 'atk': 252, 'def': 0, 'spa': 0, 'spd': 4, 'spe': 252},
                'moves': {'V-create': 0.72, 'U-turn': 0.64, 'Bolt Strike': 0.63, 'Trick': 0.29, 'Zen Headbutt': 0.27,
                          'Celebrate': 0.27, 'Stored Power': 0.27, 'Searing Shot': 0.26, 'Focus Blast': 0.26,
                          'Brick Break': 0.14, 'Glaciate': 0.07}},
    'latiasmega': {'name': 'latiasmega', 'ability': 'Levitate', 'item': 'Latiasite', 'nature': 'Timid',
                   'spread': {'hp': 252, 'atk': 0, 'def': 0, 'spa': 0, 'spd': 4, 'spe': 252},
                   'moves': {'Ice Beam': 0.7, 'Calm Mind': 0.63, 'Roost': 0.56, 'Stored Power': 0.48, 'Recover': 0.35,
                             'Surf': 0.25, 'Thunderbolt': 0.17, 'Thunder Wave': 0.15, 'Defog': 0.15, 'Psychic': 0.12,
                             'Healing Wish': 0.09, 'Hidden Power Ground': 0.08, 'Hidden Power Fire': 0.07}},
    'kyuremblack': {'name': 'kyuremblack', 'ability': 'Teravolt', 'item': 'Icium Z', 'nature': 'Brave',
                    'spread': {'hp': 252, 'atk': 252, 'def': 0, 'spa': 4, 'spd': 0, 'spe': 0},
                    'moves': {'Fusion Bolt': 0.99, 'Ice Beam': 0.95, 'Freeze Shock': 0.74, 'Roost': 0.6,
                              'Earth Power': 0.41, 'Hidden Power Fire': 0.09, 'Substitute': 0.08}},
    'lopunnymega': {'name': 'lopunnymega', 'ability': 'Scrappy', 'item': 'Lopunnite', 'nature': 'Jolly',
                    'spread': {'hp': 0, 'atk': 252, 'def': 0, 'spa': 0, 'spd': 4, 'spe': 252},
                    'moves': {'High Jump Kick': 0.99, 'Fake Out': 0.93, 'Return': 0.69, 'Power-Up Punch': 0.47,
                              'Frustration': 0.3, 'Ice Punch': 0.27, 'Quick Attack': 0.24}},
    'volcarona': {'name': 'volcarona', 'ability': 'Flame Body', 'item': 'Buginium Z', 'nature': 'Timid',
                  'spread': {'hp': 0, 'atk': 0, 'def': 0, 'spa': 252, 'spd': 4, 'spe': 252},
                  'moves': {'Quiver Dance': 0.98, 'Bug Buzz': 0.85, 'Roost': 0.6, 'Flamethrower': 0.54,
                            'Fiery Dance': 0.27, 'Hidden Power Ground': 0.26, 'Fire Blast': 0.18, 'Psychic': 0.17}},
    'tyranitar': {'name': 'tyranitar', 'ability': 'Sand Stream', 'item': 'Assault Vest', 'nature': 'Careful',
                  'spread': {'hp': 224, 'atk': 32, 'def': 0, 'spa': 0, 'spd': 252, 'spe': 0},
                  'moves': {'Pursuit': 0.91, 'Crunch': 0.76, 'Stone Edge': 0.69, 'Earthquake': 0.67, 'Rock Slide': 0.24,
                            'Stealth Rock': 0.18, 'Fire Punch': 0.12, 'Ice Beam': 0.11, 'Ice Punch': 0.08,
                            'Superpower': 0.06}},
    'pinsirmega': {'name': 'pinsirmega', 'ability': 'Aerilate', 'item': 'Pinsirite', 'nature': 'Jolly',
                   'spread': {'hp': 0, 'atk': 252, 'def': 0, 'spa': 0, 'spd': 4, 'spe': 252},
                   'moves': {'Swords Dance': 1.0, 'Quick Attack': 0.89, 'Earthquake': 0.7, 'Frustration': 0.65,
                             'Return': 0.35, 'Close Combat': 0.26}},
    'bisharp': {'name': 'bisharp', 'ability': 'Defiant', 'item': 'Leftovers', 'nature': 'Adamant',
                'spread': {'hp': 248, 'atk': 252, 'def': 0, 'spa': 0, 'spd': 4, 'spe': 4},
                'moves': {'Knock Off': 0.99, 'Iron Head': 0.99, 'Sucker Punch': 0.92, 'Swords Dance': 0.89,
                          'Pursuit': 0.1}},
    'alakazammega': {'name': 'alakazammega', 'ability': 'Trace', 'item': 'Alakazite', 'nature': 'Timid',
                     'spread': {'hp': 0, 'atk': 0, 'def': 0, 'spa': 252, 'spd': 4, 'spe': 252},
                     'moves': {'Psychic': 0.94, 'Focus Blast': 0.92, 'Recover': 0.72, 'Shadow Ball': 0.71,
                               'Calm Mind': 0.23, 'Hidden Power Fire': 0.09, 'Dazzling Gleam': 0.08,
                               'Energy Ball': 0.08, 'Psyshock': 0.07}},
    'serperior': {'name': 'serperior', 'ability': 'Contrary', 'item': 'Leftovers', 'nature': 'Timid',
                  'spread': {'hp': 0, 'atk': 0, 'def': 0, 'spa': 252, 'spd': 4, 'spe': 252},
                  'moves': {'Leaf Storm': 1.0, 'Hidden Power Fire': 0.73, 'Glare': 0.73, 'Substitute': 0.4,
                            'Defog': 0.37, 'Leech Seed': 0.26, 'Synthesis': 0.14, 'Taunt': 0.09, 'Knock Off': 0.08,
                            'Hidden Power Ground': 0.07}},
    'charizardmegax': {'name': 'charizardmegax', 'ability': 'Tough Claws', 'item': 'Charizardite X', 'nature': 'Jolly',
                       'spread': {'hp': 0, 'atk': 252, 'def': 0, 'spa': 0, 'spd': 4, 'spe': 252},
                       'moves': {'Flare Blitz': 0.88, 'Dragon Dance': 0.85, 'Earthquake': 0.81, 'Roost': 0.79,
                                 'Dragon Claw': 0.41, 'Fire Punch': 0.04, 'Outrage': 0.04}},
    'hoopaunbound': {'name': 'hoopaunbound', 'ability': 'Magician', 'item': 'Choice Band', 'nature': 'Jolly',
                     'spread': {'hp': 0, 'atk': 252, 'def': 0, 'spa': 0, 'spd': 4, 'spe': 252},
                     'moves': {'Hyperspace Fury': 0.67, 'Gunk Shot': 0.62, 'Drain Punch': 0.4, 'Zen Headbutt': 0.38,
                               'Fire Punch': 0.37, 'Psychic': 0.33, 'Dark Pulse': 0.32, 'Focus Blast': 0.3,
                               'Nasty Plot': 0.26, 'Knock Off': 0.19}},
    'reuniclus': {'name': 'reuniclus', 'ability': 'Magic Guard', 'item': 'Leftovers', 'nature': 'Bold',
                  'spread': {'hp': 252, 'atk': 0, 'def': 212, 'spa': 0, 'spd': 0, 'spe': 44},
                  'moves': {'Recover': 0.96, 'Calm Mind': 0.96, 'Psyshock': 0.69, 'Psychic': 0.31, 'Acid Armor': 0.31,
                            'Focus Blast': 0.28, 'Thunder': 0.21, 'Iron Defense': 0.09, 'Energy Ball': 0.08}},
    'dianciemega': {'name': 'dianciemega', 'ability': 'Magic Bounce', 'item': 'Diancite', 'nature': 'Hasty',
                    'spread': {'hp': 0, 'atk': 4, 'def': 0, 'spa': 252, 'spd': 0, 'spe': 252},
                    'moves': {'Moonblast': 0.93, 'Diamond Storm': 0.77, 'Protect': 0.62, 'Stealth Rock': 0.56,
                              'Earth Power': 0.52, 'Hidden Power Fire': 0.23, 'Endeavor': 0.09, 'Substitute': 0.05,
                              'Hidden Power Ice': 0.05}},
    'mew': {'name': 'mew', 'ability': 'Synchronize', 'item': 'Leftovers', 'nature': 'Modest',
            'spread': {'hp': 0, 'atk': 0, 'def': 0, 'spa': 252, 'spd': 4, 'spe': 252},
            'moves': {'Will-O-Wisp': 0.65, 'Soft-Boiled': 0.41, 'Defog': 0.35, 'Roost': 0.33, 'Earthquake': 0.29,
                      'Earth Power': 0.29, 'Ice Beam': 0.28, 'Stealth Rock': 0.27, 'Psychic': 0.25, 'Fire Blast': 0.15,
                      'Knock Off': 0.12, 'Taunt': 0.1, 'Nasty Plot': 0.08, 'Rock Polish': 0.06, 'Aura Sphere': 0.05,
                      'Block': 0.04, 'U-turn': 0.04, 'Rest': 0.04, 'Thunder Wave': 0.02}},
    'hippowdon': {'name': 'hippowdon', 'ability': 'Sand Stream', 'item': 'Leftovers', 'nature': 'Impish',
                  'spread': {'hp': 248, 'atk': 0, 'def': 248, 'spa': 0, 'spd': 0, 'spe': 8},
                  'moves': {'Earthquake': 0.99, 'Stealth Rock': 0.98, 'Slack Off': 0.98, 'Toxic': 0.73,
                            'Whirlwind': 0.25}},
    'gyaradosmega': {'name': 'gyaradosmega', 'ability': 'Mold Breaker', 'item': 'Gyaradosite', 'nature': 'Jolly',
                     'spread': {'hp': 0, 'atk': 252, 'def': 0, 'spa': 0, 'spd': 4, 'spe': 252},
                     'moves': {'Dragon Dance': 1.0, 'Earthquake': 0.81, 'Crunch': 0.71, 'Substitute': 0.55,
                               'Waterfall': 0.5, 'Taunt': 0.24}},
    'manaphy': {'name': 'manaphy', 'ability': 'Hydration', 'item': 'Leftovers', 'nature': 'Modest',
                'spread': {'hp': 184, 'atk': 0, 'def': 0, 'spa': 252, 'spd': 0, 'spe': 72},
                'moves': {'Tail Glow': 0.99, 'Surf': 0.96, 'Psychic': 0.77, 'Rain Dance': 0.59, 'Ice Beam': 0.33,
                          'Rest': 0.28}},
    'charizardmegay': {'name': 'charizardmegay', 'ability': 'Drought', 'item': 'Charizardite Y', 'nature': 'Timid',
                       'spread': {'hp': 0, 'atk': 0, 'def': 0, 'spa': 252, 'spd': 4, 'spe': 252},
                       'moves': {'Roost': 0.88, 'Solar Beam': 0.81, 'Flamethrower': 0.78, 'Focus Blast': 0.77,
                                 'Fire Blast': 0.23, 'Defog': 0.19, 'Hidden Power Ground': 0.12, 'Earthquake': 0.04}},
    'azumarill': {'name': 'azumarill', 'ability': 'Huge Power', 'item': 'Normalium Z', 'nature': 'Adamant',
                  'spread': {'hp': 248, 'atk': 252, 'def': 0, 'spa': 0, 'spd': 8, 'spe': 0},
                  'moves': {'Knock Off': 0.75, 'Aqua Jet': 0.73, 'Belly Drum': 0.63, 'Liquidation': 0.55,
                            'Play Rough': 0.23, 'Whirlpool': 0.22, 'Perish Song': 0.22, 'Protect': 0.22, 'Toxic': 0.18,
                            'Rest': 0.08}},
    'weavile': {'name': 'weavile', 'ability': 'Pressure', 'item': 'Choice Band', 'nature': 'Jolly',
                'spread': {'hp': 0, 'atk': 252, 'def': 0, 'spa': 0, 'spd': 4, 'spe': 252},
                'moves': {'Knock Off': 0.99, 'Icicle Crash': 0.98, 'Pursuit': 0.92, 'Ice Shard': 0.77,
                          'Foul Play': 0.14}},
    'amoonguss': {'name': 'amoonguss', 'ability': 'Regenerator', 'item': 'Black Sludge', 'nature': 'Calm',
                  'spread': {'hp': 248, 'atk': 0, 'def': 44, 'spa': 0, 'spd': 216, 'spe': 0},
                  'moves': {'Hidden Power Fire': 0.95, 'Giga Drain': 0.94, 'Spore': 0.56, 'Clear Smog': 0.49,
                            'Stun Spore': 0.45, 'Sludge Bomb': 0.45}},
    'blacephalon': {'name': 'blacephalon', 'ability': 'Beast Boost', 'item': 'Choice Scarf', 'nature': 'Timid',
                    'spread': {'hp': 0, 'atk': 0, 'def': 0, 'spa': 252, 'spd': 4, 'spe': 252},
                    'moves': {'Shadow Ball': 1.0, 'Flamethrower': 0.83, 'Trick': 0.52, 'Fire Blast': 0.28,
                              'Substitute': 0.26, 'Calm Mind': 0.25, 'Mind Blown': 0.24, 'Overheat': 0.19,
                              'Psyshock': 0.1, 'Flame Charge': 0.06, 'Knock Off': 0.05, 'Hidden Power Ice': 0.04}},
    'quagsire': {'name': 'quagsire', 'ability': 'Unaware', 'item': 'Leftovers', 'nature': 'Impish',
                 'spread': {'hp': 252, 'atk': 4, 'def': 252, 'spa': 0, 'spd': 0, 'spe': 0},
                 'moves': {'Recover': 1.0, 'Scald': 1.0, 'Earthquake': 0.65, 'Toxic': 0.63, 'Curse': 0.36,
                           'Amnesia': 0.32}},
    'volcanion': {'name': 'volcanion', 'ability': 'Water Absorb', 'item': 'Assault Vest', 'nature': 'Brave',
                  'spread': {'hp': 248, 'atk': 140, 'def': 0, 'spa': 120, 'spd': 0, 'spe': 0},
                  'moves': {'Steam Eruption': 0.99, 'Fire Blast': 0.79, 'Explosion': 0.65, 'Superpower': 0.5,
                            'Earth Power': 0.28, 'Defog': 0.28, 'Overheat': 0.15, 'Focus Blast': 0.15, 'Toxic': 0.06}},
    'mimikyu': {'name': 'mimikyu', 'ability': 'Disguise', 'item': 'Life Orb', 'nature': 'Adamant',
                'spread': {'hp': 0, 'atk': 252, 'def': 0, 'spa': 0, 'spd': 4, 'spe': 252},
                'moves': {'Play Rough': 0.97, 'Shadow Claw': 0.94, 'Swords Dance': 0.92, 'Shadow Sneak': 0.87,
                          'Trick Room': 0.13}},
    'alomomola': {'name': 'alomomola', 'ability': 'Regenerator', 'item': 'Leftovers', 'nature': 'Bold',
                  'spread': {'hp': 40, 'atk': 0, 'def': 216, 'spa': 0, 'spd': 252, 'spe': 0},
                  'moves': {'Wish': 1.0, 'Protect': 0.98, 'Toxic': 0.95, 'Knock Off': 0.5, 'Scald': 0.33,
                            'Liquidation': 0.22}},
    'hydreigon': {'name': 'hydreigon', 'ability': 'Levitate', 'item': 'Darkinium Z', 'nature': 'Timid',
                  'spread': {'hp': 0, 'atk': 0, 'def': 0, 'spa': 252, 'spd': 4, 'spe': 252},
                  'moves': {'Dark Pulse': 0.99, 'Roost': 0.75, 'Earth Power': 0.64, 'Defog': 0.43, 'Draco Meteor': 0.32,
                            'Fire Blast': 0.2, 'Flash Cannon': 0.2, 'U-turn': 0.2, 'Flamethrower': 0.18}},
    'tyranitarmega': {'name': 'tyranitarmega', 'ability': 'Sand Stream', 'item': 'Tyranitarite', 'nature': 'Jolly',
                      'spread': {'hp': 0, 'atk': 252, 'def': 0, 'spa': 0, 'spd': 4, 'spe': 252},
                      'moves': {'Stone Edge': 0.9, 'Fire Punch': 0.65, 'Ice Punch': 0.61, 'Dragon Dance': 0.48,
                                'Pursuit': 0.45, 'Stealth Rock': 0.43, 'Earthquake': 0.3}},
    'mukalola': {'name': 'mukalola', 'ability': 'Poison Touch', 'item': 'Assault Vest', 'nature': 'Adamant',
                 'spread': {'hp': 248, 'atk': 252, 'def': 4, 'spa': 0, 'spd': 0, 'spe': 4},
                 'moves': {'Knock Off': 1.0, 'Pursuit': 0.96, 'Fire Punch': 0.51, 'Recycle': 0.36, 'Gunk Shot': 0.36,
                           'Poison Fang': 0.33, 'Poison Jab': 0.3}},
    'latiosmega': {'name': 'latiosmega', 'ability': 'Levitate', 'item': 'Latiosite', 'nature': 'Naive',
                   'spread': {'hp': 0, 'atk': 4, 'def': 0, 'spa': 252, 'spd': 0, 'spe': 252},
                   'moves': {'Psychic': 0.88, 'Earthquake': 0.67, 'Recover': 0.5, 'Ice Beam': 0.47, 'Roost': 0.46,
                             'Calm Mind': 0.26, 'Surf': 0.25, 'Draco Meteor': 0.24, 'Psyshock': 0.07}},
    'slowbromega': {'name': 'slowbromega', 'ability': 'Shell Armor', 'item': 'Slowbronite', 'nature': 'Bold',
                    'spread': {'hp': 248, 'atk': 0, 'def': 216, 'spa': 0, 'spd': 0, 'spe': 44},
                    'moves': {'Scald': 0.99, 'Slack Off': 0.99, 'Ice Beam': 0.46, 'Psychic': 0.38, 'Flamethrower': 0.34,
                              'Psyshock': 0.25, 'Calm Mind': 0.24, 'Fire Blast': 0.19}},
    'ditto': {'name': 'ditto', 'ability': 'Imposter', 'item': 'Choice Scarf', 'nature': 'Hardy',
              'spread': {'hp': 252, 'atk': 0, 'def': 0, 'spa': 0, 'spd': 0, 'spe': 0}, 'moves': {'Nothing': 3.0}},
    'garchompmega': {'name': 'garchompmega', 'ability': 'Sand Force', 'item': 'Garchompite', 'nature': 'Jolly',
                     'spread': {'hp': 0, 'atk': 252, 'def': 0, 'spa': 0, 'spd': 4, 'spe': 252},
                     'moves': {'Earthquake': 0.92, 'Swords Dance': 0.92, 'Stone Edge': 0.75, 'Fire Fang': 0.67,
                               'Dragon Claw': 0.15, 'Stealth Rock': 0.14, 'Dragon Tail': 0.08, 'Stomping Tantrum': 0.08,
                               'Rest': 0.05, 'Fire Blast': 0.04}},
    'kommoo': {'name': 'kommoo', 'ability': 'Bulletproof', 'item': 'Kommonium Z', 'nature': 'Jolly',
               'spread': {'hp': 52, 'atk': 204, 'def': 0, 'spa': 0, 'spd': 0, 'spe': 252},
               'moves': {'Clanging Scales': 0.54, 'Close Combat': 0.5, 'Poison Jab': 0.45, 'Drain Punch': 0.41,
                         'Substitute': 0.36, 'Belly Drum': 0.34, 'Dragon Dance': 0.31, 'Thunder Punch': 0.29,
                         'Stealth Rock': 0.25, 'Flamethrower': 0.17, 'Protect': 0.07, 'Earthquake': 0.07,
                         'Flash Cannon': 0.06}},
    'thundurustherian': {'name': 'thundurustherian', 'ability': 'Volt Absorb', 'item': 'Fightinium Z',
                         'nature': 'Timid', 'spread': {'hp': 0, 'atk': 0, 'def': 0, 'spa': 252, 'spd': 4, 'spe': 252},
                         'moves': {'Thunderbolt': 0.8, 'Hidden Power Ice': 0.65, 'Nasty Plot': 0.64,
                                   'Focus Blast': 0.57, 'Hidden Power Flying': 0.33, 'Grass Knot': 0.18,
                                   'Volt Switch': 0.16, 'Discharge': 0.15, 'Superpower': 0.15, 'Agility': 0.11,
                                   'Sludge Wave': 0.11}},
    'terrakion': {'name': 'terrakion', 'ability': 'Justified', 'item': 'Rockium Z', 'nature': 'Jolly',
                  'spread': {'hp': 0, 'atk': 248, 'def': 0, 'spa': 0, 'spd': 8, 'spe': 252},
                  'moves': {'Close Combat': 1.0, 'Stone Edge': 1.0, 'Swords Dance': 0.68, 'Stealth Rock': 0.65,
                            'Quick Attack': 0.17, 'Earthquake': 0.16, 'Iron Head': 0.15}},
    'gengar': {'name': 'gengar', 'ability': 'Cursed Body', 'item': 'Life Orb', 'nature': 'Timid',
               'spread': {'hp': 0, 'atk': 0, 'def': 0, 'spa': 252, 'spd': 4, 'spe': 252},
               'moves': {'Shadow Ball': 0.94, 'Focus Blast': 0.93, 'Sludge Wave': 0.78, 'Destiny Bond': 0.67,
                         'Substitute': 0.2, 'Thunder': 0.17, 'Trick': 0.08, 'Sludge Bomb': 0.06}},
    'suicune': {'name': 'suicune', 'ability': 'Pressure', 'item': 'Leftovers', 'nature': 'Bold',
                'spread': {'hp': 252, 'atk': 0, 'def': 252, 'spa': 0, 'spd': 4, 'spe': 0},
                'moves': {'Scald': 0.99, 'Calm Mind': 0.89, 'Protect': 0.53, 'Substitute': 0.52, 'Rest': 0.46,
                          'Roar': 0.26, 'Toxic': 0.18}},
    'kingdra': {'name': 'kingdra', 'ability': 'Swift Swim', 'item': 'Choice Specs', 'nature': 'Modest',
                'spread': {'hp': 0, 'atk': 0, 'def': 0, 'spa': 252, 'spd': 4, 'spe': 252},
                'moves': {'Draco Meteor': 0.99, 'Hydro Pump': 0.94, 'Surf': 0.94, 'Ice Beam': 0.9,
                          'Hidden Power Grass': 0.07}},
    'kyurem': {'name': 'kyurem', 'ability': 'Pressure', 'item': 'Metronome', 'nature': 'Timid',
               'spread': {'hp': 56, 'atk': 0, 'def': 0, 'spa': 200, 'spd': 0, 'spe': 252},
               'moves': {'Ice Beam': 1.0, 'Earth Power': 1.0, 'Roost': 0.99, 'Substitute': 0.99}},
    'gastrodon': {'name': 'gastrodon', 'ability': 'Storm Drain', 'item': 'Leftovers', 'nature': 'Sassy',
                  'spread': {'hp': 252, 'atk': 0, 'def': 4, 'spa': 0, 'spd': 252, 'spe': 0},
                  'moves': {'Recover': 1.0, 'Scald': 0.88, 'Toxic': 0.86, 'Earthquake': 0.79, 'Earth Power': 0.16,
                            'Clear Smog': 0.12}},
    'ribombee': {'name': 'ribombee', 'ability': 'Shield Dust', 'item': 'Focus Sash', 'nature': 'Timid',
                 'spread': {'hp': 0, 'atk': 0, 'def': 0, 'spa': 252, 'spd': 4, 'spe': 252},
                 'moves': {'Sticky Web': 1.0, 'Moonblast': 0.99, 'Stun Spore': 0.83, 'Hidden Power Fire': 0.83,
                           'Quiver Dance': 0.13, 'Hidden Power Ground': 0.11}},
    'buzzwole': {'name': 'buzzwole', 'ability': 'Beast Boost', 'item': 'Groundium Z', 'nature': 'Impish',
                 'spread': {'hp': 232, 'atk': 44, 'def': 232, 'spa': 0, 'spd': 0, 'spe': 0},
                 'moves': {'Roost': 0.92, 'Ice Punch': 0.83, 'Drain Punch': 0.79, 'Earthquake': 0.67, 'Bulk Up': 0.28,
                           'Substitute': 0.14, 'Focus Punch': 0.14, 'Superpower': 0.05}},
    'dragonite': {'name': 'dragonite', 'ability': 'Multiscale', 'item': 'Flyinium Z', 'nature': 'Adamant',
                  'spread': {'hp': 0, 'atk': 252, 'def': 0, 'spa': 0, 'spd': 4, 'spe': 252},
                  'moves': {'Dragon Dance': 0.86, 'Earthquake': 0.79, 'Extreme Speed': 0.64, 'Fly': 0.51,
                            'Fire Punch': 0.32, 'Roost': 0.23, 'Outrage': 0.22, 'Dragon Claw': 0.12, 'Ice Punch': 0.06,
                            'Substitute': 0.05, 'Hurricane': 0.03}},
    'slowbro': {'name': 'slowbro', 'ability': 'Regenerator', 'item': 'Leftovers', 'nature': 'Bold',
                'spread': {'hp': 252, 'atk': 0, 'def': 252, 'spa': 0, 'spd': 4, 'spe': 0},
                'moves': {'Scald': 0.99, 'Slack Off': 0.79, 'Ice Beam': 0.54, 'Psychic': 0.22, 'Future Sight': 0.19,
                          'Flamethrower': 0.18, 'Psyshock': 0.18, 'Toxic': 0.17, 'Calm Mind': 0.16, 'Counter': 0.11,
                          'Focus Blast': 0.09, 'Thunder Wave': 0.09, 'Protect': 0.08, 'Fire Blast': 0.08}},
    'marowakalola': {'name': 'marowakalola', 'ability': 'Lightning Rod', 'item': 'Thick Club', 'nature': 'Brave',
                     'spread': {'hp': 248, 'atk': 252, 'def': 0, 'spa': 0, 'spd': 8, 'spe': 0},
                     'moves': {'Shadow Bone': 1.0, 'Flare Blitz': 0.57, 'Fire Punch': 0.42, 'Swords Dance': 0.41,
                               'Substitute': 0.39, 'Focus Punch': 0.34, 'Earthquake': 0.31, 'Bonemerang': 0.27,
                               'Stealth Rock': 0.13}},
    'gallademega': {'name': 'gallademega', 'ability': 'Inner Focus', 'item': 'Galladite', 'nature': 'Jolly',
                    'spread': {'hp': 0, 'atk': 252, 'def': 0, 'spa': 0, 'spd': 4, 'spe': 252},
                    'moves': {'Swords Dance': 0.98, 'Zen Headbutt': 0.95, 'Close Combat': 0.93, 'Knock Off': 0.7,
                              'Ice Punch': 0.24, 'Drain Punch': 0.07}},
    'seismitoad': {'name': 'seismitoad', 'ability': 'Water Absorb', 'item': 'Leftovers', 'nature': 'Relaxed',
                   'spread': {'hp': 252, 'atk': 0, 'def': 252, 'spa': 0, 'spd': 4, 'spe': 0},
                   'moves': {'Stealth Rock': 1.0, 'Earthquake': 0.94, 'Toxic': 0.93, 'Scald': 0.84, 'Knock Off': 0.2}},
    'araquanid': {'name': 'araquanid', 'ability': 'Water Bubble', 'item': 'Choice Band', 'nature': 'Adamant',
                  'spread': {'hp': 248, 'atk': 252, 'def': 0, 'spa': 0, 'spd': 8, 'spe': 0},
                  'moves': {'Liquidation': 1.0, 'Sticky Web': 0.72, 'Leech Life': 0.64, 'Toxic': 0.55,
                            'Poison Jab': 0.3, 'Magic Coat': 0.26, 'Infestation': 0.12, 'Mirror Coat': 0.1,
                            'Rest': 0.08, 'Substitute': 0.06}},
    'heracrossmega': {'name': 'heracrossmega', 'ability': 'Skill Link', 'item': 'Heracronite', 'nature': 'Adamant',
                      'spread': {'hp': 0, 'atk': 252, 'def': 0, 'spa': 0, 'spd': 4, 'spe': 252},
                      'moves': {'Close Combat': 0.99, 'Rock Blast': 0.98, 'Pin Missile': 0.82, 'Swords Dance': 0.76,
                                'Substitute': 0.24, 'Bullet Seed': 0.15}},
    'gyarados': {'name': 'gyarados', 'ability': 'Moxie', 'item': 'Flyinium Z', 'nature': 'Jolly',
                 'spread': {'hp': 0, 'atk': 252, 'def': 0, 'spa': 0, 'spd': 4, 'spe': 252},
                 'moves': {'Waterfall': 0.96, 'Dragon Dance': 0.96, 'Bounce': 0.92, 'Earthquake': 0.53,
                           'Substitute': 0.27, 'Stone Edge': 0.12, 'Taunt': 0.1}},
    'mamoswine': {'name': 'mamoswine', 'ability': 'Thick Fat', 'item': 'Life Orb', 'nature': 'Naive',
                  'spread': {'hp': 0, 'atk': 252, 'def': 0, 'spa': 4, 'spd': 0, 'spe': 252},
                  'moves': {'Earthquake': 1.0, 'Ice Shard': 0.97, 'Icicle Crash': 0.92, 'Stealth Rock': 0.45,
                            'Freeze-Dry': 0.26, 'Knock Off': 0.2, 'Superpower': 0.12}},
    'cresselia': {'name': 'cresselia', 'ability': 'Levitate', 'item': 'Mental Herb', 'nature': 'Relaxed',
                  'spread': {'hp': 248, 'atk': 0, 'def': 252, 'spa': 0, 'spd': 8, 'spe': 0},
                  'moves': {'Ice Beam': 0.91, 'Moonlight': 0.89, 'Trick Room': 0.77, 'Lunar Dance': 0.74,
                            'Thunder Wave': 0.22, 'Toxic': 0.14, 'Psychic': 0.11, 'Magic Coat': 0.08}},
    'ninetalesalola': {'name': 'ninetalesalola', 'ability': 'Snow Warning', 'item': 'Light Clay', 'nature': 'Timid',
                       'spread': {'hp': 252, 'atk': 0, 'def': 0, 'spa': 4, 'spd': 0, 'spe': 252},
                       'moves': {'Aurora Veil': 0.99, 'Freeze-Dry': 0.94, 'Hypnosis': 0.75, 'Hail': 0.67,
                                 'Moonblast': 0.18, 'Blizzard': 0.11, 'Encore': 0.1, 'Safeguard': 0.09}},
    'crawdaunt': {'name': 'crawdaunt', 'ability': 'Adaptability', 'item': 'Choice Band', 'nature': 'Adamant',
                  'spread': {'hp': 0, 'atk': 252, 'def': 4, 'spa': 0, 'spd': 0, 'spe': 252},
                  'moves': {'Knock Off': 1.0, 'Aqua Jet': 1.0, 'Crabhammer': 0.94, 'Crunch': 0.39, 'Swords Dance': 0.37,
                            'Superpower': 0.18}},
    'scizor': {'name': 'scizor', 'ability': 'Technician', 'item': 'Choice Band', 'nature': 'Adamant',
               'spread': {'hp': 240, 'atk': 252, 'def': 0, 'spa': 0, 'spd': 0, 'spe': 16},
               'moves': {'Bullet Punch': 1.0, 'U-turn': 0.93, 'Superpower': 0.89, 'Pursuit': 0.74, 'Swords Dance': 0.14,
                         'Knock Off': 0.1}},
    'politoed': {'name': 'politoed', 'ability': 'Drizzle', 'item': 'Leftovers', 'nature': 'Calm',
                 'spread': {'hp': 248, 'atk': 0, 'def': 0, 'spa': 8, 'spd': 252, 'spe': 0},
                 'moves': {'Protect': 0.97, 'Rest': 0.97, 'Perish Song': 0.97, 'Whirlpool': 0.96}},
    'sharpedomega': {'name': 'sharpedomega', 'ability': 'Strong Jaw', 'item': 'Sharpedonite', 'nature': 'Adamant',
                     'spread': {'hp': 0, 'atk': 252, 'def': 0, 'spa': 0, 'spd': 4, 'spe': 252},
                     'moves': {'Crunch': 1.0, 'Protect': 0.99, 'Psychic Fangs': 0.92, 'Ice Fang': 0.91}},
    'mantine': {'name': 'mantine', 'ability': 'Water Absorb', 'item': 'Leftovers', 'nature': 'Calm',
                'spread': {'hp': 248, 'atk': 0, 'def': 244, 'spa': 0, 'spd': 16, 'spe': 0},
                'moves': {'Scald': 1.0, 'Roost': 1.0, 'Defog': 0.98, 'Haze': 0.55, 'Toxic': 0.38}},
    'thundurus': {'name': 'thundurus', 'ability': 'Prankster', 'item': 'Leftovers', 'nature': 'Timid',
                  'spread': {'hp': 0, 'atk': 0, 'def': 0, 'spa': 252, 'spd': 4, 'spe': 252},
                  'moves': {'Hidden Power Ice': 0.88, 'Thunderbolt': 0.81, 'Nasty Plot': 0.57, 'Focus Blast': 0.55,
                            'Superpower': 0.32, 'Knock Off': 0.25, 'Wild Charge': 0.13, 'Thunder Wave': 0.08,
                            'Fly': 0.08, 'Incinerate': 0.06, 'Sludge Wave': 0.06, 'Volt Switch': 0.04}},
    'latios': {'name': 'latios', 'ability': 'Levitate', 'item': 'Choice Scarf', 'nature': 'Timid',
               'spread': {'hp': 0, 'atk': 0, 'def': 0, 'spa': 252, 'spd': 4, 'spe': 252},
               'moves': {'Draco Meteor': 0.73, 'Psyshock': 0.48, 'Defog': 0.44, 'Psychic': 0.32, 'Roost': 0.26,
                         'Trick': 0.25, 'Surf': 0.23, 'Ice Beam': 0.2, 'Recover': 0.18, 'Hidden Power Fire': 0.17,
                         'Thunderbolt': 0.15, 'Earthquake': 0.14, 'Memento': 0.1, 'Reflect': 0.09,
                         'Light Screen': 0.09}},
    'altariamega': {'name': 'altariamega', 'ability': 'Pixilate', 'item': 'Altarianite', 'nature': 'Impish',
                    'spread': {'hp': 248, 'atk': 0, 'def': 136, 'spa': 0, 'spd': 80, 'spe': 44},
                    'moves': {'Roost': 0.99, 'Body Slam': 0.69, 'Earthquake': 0.64, 'Heal Bell': 0.53,
                              'Dragon Dance': 0.21, 'Defog': 0.2, 'Frustration': 0.18, 'Haze': 0.14, 'Toxic': 0.11,
                              'Flamethrower': 0.07, 'Fire Blast': 0.07}},
    'manectricmega': {'name': 'manectricmega', 'ability': 'Intimidate', 'item': 'Manectite', 'nature': 'Timid',
                      'spread': {'hp': 0, 'atk': 0, 'def': 0, 'spa': 252, 'spd': 4, 'spe': 252},
                      'moves': {'Volt Switch': 0.99, 'Hidden Power Ice': 0.98, 'Thunderbolt': 0.94,
                                'Flamethrower': 0.67, 'Overheat': 0.33}},
    'pyukumuku': {'name': 'pyukumuku', 'ability': 'Unaware', 'item': 'Leftovers', 'nature': 'Bold',
                  'spread': {'hp': 252, 'atk': 0, 'def': 252, 'spa': 0, 'spd': 4, 'spe': 0},
                  'moves': {'Recover': 0.97, 'Block': 0.97, 'Spite': 0.62, 'Rest': 0.44, 'Toxic': 0.4, 'Soak': 0.32,
                            'Counter': 0.18}},
    'sceptilemega': {'name': 'sceptilemega', 'ability': 'Lightning Rod', 'item': 'Sceptilite', 'nature': 'Timid',
                     'spread': {'hp': 0, 'atk': 0, 'def': 0, 'spa': 252, 'spd': 4, 'spe': 252},
                     'moves': {'Dragon Pulse': 0.98, 'Leaf Storm': 0.85, 'Hidden Power Fire': 0.79, 'Focus Blast': 0.58,
                               'Earthquake': 0.33, 'Giga Drain': 0.1, 'Substitute': 0.08, 'Leech Seed': 0.07,
                               'Nature Power': 0.05}},
    'breloom': {'name': 'breloom', 'ability': 'Technician', 'item': 'Life Orb', 'nature': 'Jolly',
                'spread': {'hp': 0, 'atk': 252, 'def': 0, 'spa': 0, 'spd': 4, 'spe': 252},
                'moves': {'Mach Punch': 0.8, 'Bullet Seed': 0.78, 'Spore': 0.74, 'Swords Dance': 0.7,
                          'Drain Punch': 0.23, 'Rock Tomb': 0.21, 'Facade': 0.15, 'Superpower': 0.1, 'Substitute': 0.06,
                          'Leech Seed': 0.06}},
    'zygarde10%': {'name': 'zygarde10%', 'ability': 'Aura Break', 'item': 'Choice Band', 'nature': 'Adamant',
                   'spread': {'hp': 0, 'atk': 252, 'def': 0, 'spa': 0, 'spd': 4, 'spe': 252},
                   'moves': {'Thousand Arrows': 1.0, 'Extreme Speed': 0.84, 'Toxic': 0.73, 'Iron Tail': 0.58,
                             'Outrage': 0.3, 'Superpower': 0.14, 'Glare': 0.14, 'Rock Slide': 0.12}},
    'nihilego': {'name': 'nihilego', 'ability': 'Beast Boost', 'item': 'Choice Scarf', 'nature': 'Timid',
                 'spread': {'hp': 68, 'atk': 0, 'def': 0, 'spa': 184, 'spd': 4, 'spe': 252},
                 'moves': {'Power Gem': 0.98, 'Sludge Wave': 0.85, 'Toxic Spikes': 0.8, 'Grass Knot': 0.49,
                           'Hidden Power Fire': 0.24, 'Hidden Power Ice': 0.18, 'Stealth Rock': 0.16, 'Thunder': 0.08}},
    'starmie': {'name': 'starmie', 'ability': 'Natural Cure', 'item': 'Colbur Berry', 'nature': 'Timid',
                'spread': {'hp': 248, 'atk': 0, 'def': 0, 'spa': 0, 'spd': 44, 'spe': 216},
                'moves': {'Rapid Spin': 0.93, 'Recover': 0.75, 'Scald': 0.72, 'Thunderbolt': 0.46, 'Hydro Pump': 0.23,
                          'Ice Beam': 0.23, 'Psyshock': 0.12, 'Thunder Wave': 0.12, 'Toxic': 0.09, 'Psychic': 0.07,
                          'Thunder': 0.05, 'Blizzard': 0.04}},
    'diggersby': {'name': 'diggersby', 'ability': 'Huge Power', 'item': 'Choice Band', 'nature': 'Adamant',
                  'spread': {'hp': 0, 'atk': 252, 'def': 0, 'spa': 0, 'spd': 4, 'spe': 252},
                  'moves': {'Earthquake': 0.99, 'Quick Attack': 0.98, 'Return': 0.56, 'Spikes': 0.41,
                            'Frustration': 0.39, 'Fire Punch': 0.22, 'Swords Dance': 0.2, 'Knock Off': 0.09}},
    'shedinja': {'name': 'shedinja', 'ability': 'Wonder Guard', 'item': 'Focus Sash', 'nature': 'Mild',
                 'spread': {'hp': 0, 'atk': 0, 'def': 0, 'spa': 252, 'spd': 0, 'spe': 252},
                 'moves': {'Will-O-Wisp': 0.99, 'Protect': 0.99, 'Toxic': 0.8, 'Shadow Ball': 0.62,
                           'Shadow Sneak': 0.25, 'X-Scissor': 0.12, 'Heal Block': 0.08}},
    'beedrillmega': {'name': 'beedrillmega', 'ability': 'Adaptability', 'item': 'Beedrillite', 'nature': 'Jolly',
                     'spread': {'hp': 0, 'atk': 252, 'def': 0, 'spa': 0, 'spd': 4, 'spe': 252},
                     'moves': {'Poison Jab': 1.0, 'Drill Run': 0.95, 'U-turn': 0.95, 'Swords Dance': 0.4,
                               'Knock Off': 0.39, 'Fell Stinger': 0.16}}}
